
[uuid(A79A3513-2403-4a31-BBC2-A5A7501DAD71),
pointer_default(unique)] 

interface CamSvc
{
	cpp_quote ("#define CAM_PROTOCOL_SEQUENCE L\"ncacn_ip_tcp\"")
	cpp_quote ("#define CAM_END_PORT L\"4848\"")	
	
	int
	RpcCamJoinComputeNode(
		[in] handle_t hBinding,
		[in, string]wchar_t* pszFQDN,
		[out, string]wchar_t** ppszMachinePassword
		);	
}