#include "includes.h"

#define CASE_RETURN_STRING(token)               \
    case token:                                 \
    return #token

#define DEFAULT_RETURN_UNKNOWN_STRING()         \
    default:                                    \
    return "*UNKNOWN*"

PCSTR
GetErrorToString(DWORD dwError)
{
    switch (dwError)
    {
        CASE_RETURN_STRING(LWUTIL_ERROR_SUCCESS);
        /* Begin macadutil errors */
        CASE_RETURN_STRING(LWUTIL_ERROR_NOT_IMPLEMENTED);
        CASE_RETURN_STRING(LWUTIL_ERROR_INVALID_PARAMETER);
        CASE_RETURN_STRING(LWUTIL_ERROR_NOT_SUPPORTED);
        CASE_RETURN_STRING(LWUTIL_ERROR_LOGON_FAILURE);
        CASE_RETURN_STRING(LWUTIL_ERROR_INVALID_NAME);
        CASE_RETURN_STRING(LWUTIL_ERROR_UPN_NOT_FOUND);
        CASE_RETURN_STRING(LWUTIL_ERROR_NULL_PARAMETER);
        CASE_RETURN_STRING(LWUTIL_ERROR_INVALID_TAG);
        CASE_RETURN_STRING(LWUTIL_ERROR_NO_SUCH_ATTRIBUTE);
        CASE_RETURN_STRING(LWUTIL_ERROR_INVALID_RECORD_TYPE);
        CASE_RETURN_STRING(LWUTIL_ERROR_INVALID_ATTRIBUTE_TYPE);
        CASE_RETURN_STRING(LWUTIL_ERROR_INSUFFICIENT_BUFFER);
        CASE_RETURN_STRING(LWUTIL_ERROR_IPC_FAILED);
        CASE_RETURN_STRING(LWUTIL_ERROR_NO_PROC_STATUS);
        CASE_RETURN_STRING(LWUTIL_ERROR_KRB5_PASSWORD_MISMATCH);
        CASE_RETURN_STRING(LWUTIL_ERROR_KRB5_PASSWORD_EXPIRED);
        CASE_RETURN_STRING(LWUTIL_ERROR_KRB5_CLOCK_SKEW);
        CASE_RETURN_STRING(LWUTIL_ERROR_KRB5_ERROR);
        CASE_RETURN_STRING(LWUTIL_ERROR_GSS_API_FAILED);
        CASE_RETURN_STRING(LWUTIL_ERROR_NO_SUCH_POLICY);
        CASE_RETURN_STRING(LWUTIL_ERROR_LDAP_OPEN);
        CASE_RETURN_STRING(LWUTIL_ERROR_LDAP_SET_OPTION);
        CASE_RETURN_STRING(LWUTIL_ERROR_LDAP_QUERY_FAILED);
        CASE_RETURN_STRING(LWUTIL_ERROR_UID_NOT_FOUND);
        CASE_RETURN_STRING(LWUTIL_ERROR_MEMORY_ALLOC);
        /* End macadutil errors */
        /* Begin LSASS errors */
        CASE_RETURN_STRING(LW_ERROR_INVALID_CACHE_PATH);
        CASE_RETURN_STRING(LW_ERROR_INVALID_CONFIG_PATH);
        CASE_RETURN_STRING(LW_ERROR_INVALID_PREFIX_PATH);
        CASE_RETURN_STRING(LW_ERROR_INSUFFICIENT_BUFFER);
        CASE_RETURN_STRING(LW_ERROR_OUT_OF_MEMORY);
        CASE_RETURN_STRING(LW_ERROR_INVALID_MESSAGE);
        CASE_RETURN_STRING(LW_ERROR_UNEXPECTED_MESSAGE);
        CASE_RETURN_STRING(LW_ERROR_NO_SUCH_USER);
        CASE_RETURN_STRING(LW_ERROR_DATA_ERROR);
        CASE_RETURN_STRING(LW_ERROR_NOT_IMPLEMENTED);
        CASE_RETURN_STRING(LW_ERROR_NO_CONTEXT_ITEM);
        CASE_RETURN_STRING(LW_ERROR_NO_SUCH_GROUP);
        CASE_RETURN_STRING(LW_ERROR_REGEX_COMPILE_FAILED);
        CASE_RETURN_STRING(LW_ERROR_NSS_EDIT_FAILED);
        CASE_RETURN_STRING(LW_ERROR_NO_HANDLER);
        CASE_RETURN_STRING(LW_ERROR_INTERNAL);
        CASE_RETURN_STRING(LW_ERROR_NOT_HANDLED);
        CASE_RETURN_STRING(LW_ERROR_INVALID_DNS_RESPONSE);
        CASE_RETURN_STRING(LW_ERROR_DNS_RESOLUTION_FAILED);
        CASE_RETURN_STRING(LW_ERROR_FAILED_TIME_CONVERSION);
        CASE_RETURN_STRING(LW_ERROR_INVALID_SID);
        CASE_RETURN_STRING(LW_ERROR_PASSWORD_MISMATCH);
        CASE_RETURN_STRING(LW_ERROR_UNEXPECTED_DB_RESULT);
        CASE_RETURN_STRING(LW_ERROR_PASSWORD_EXPIRED);
        CASE_RETURN_STRING(LW_ERROR_ACCOUNT_EXPIRED);
        CASE_RETURN_STRING(LW_ERROR_USER_EXISTS);
        CASE_RETURN_STRING(LW_ERROR_GROUP_EXISTS);
        CASE_RETURN_STRING(LW_ERROR_INVALID_GROUP_INFO_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_INVALID_USER_INFO_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_UNSUPPORTED_USER_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_UNSUPPORTED_GROUP_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LOGIN_ID);
        CASE_RETURN_STRING(LW_ERROR_INVALID_HOMEDIR);
        CASE_RETURN_STRING(LW_ERROR_INVALID_GROUP_NAME);
        CASE_RETURN_STRING(LW_ERROR_NO_MORE_GROUPS);
        CASE_RETURN_STRING(LW_ERROR_NO_MORE_USERS);
        CASE_RETURN_STRING(LW_ERROR_FAILED_ADD_USER);
        CASE_RETURN_STRING(LW_ERROR_FAILED_ADD_GROUP);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LSA_CONNECTION);
        CASE_RETURN_STRING(LW_ERROR_INVALID_AUTH_PROVIDER);
        CASE_RETURN_STRING(LW_ERROR_INVALID_PARAMETER);
        CASE_RETURN_STRING(LW_ERROR_LDAP_NO_PARENT_DN);
        CASE_RETURN_STRING(LW_ERROR_LDAP_ERROR);
        CASE_RETURN_STRING(LW_ERROR_NO_SUCH_DOMAIN);
        CASE_RETURN_STRING(LW_ERROR_LDAP_FAILED_GETDN);
        CASE_RETURN_STRING(LW_ERROR_DUPLICATE_DOMAINNAME);
        CASE_RETURN_STRING(LW_ERROR_KRB5_CALL_FAILED);
        CASE_RETURN_STRING(LW_ERROR_GSS_CALL_FAILED);
        CASE_RETURN_STRING(LW_ERROR_FAILED_FIND_DC);
        CASE_RETURN_STRING(LW_ERROR_NO_SUCH_CELL);
        CASE_RETURN_STRING(LW_ERROR_GROUP_IN_USE);
        CASE_RETURN_STRING(LW_ERROR_FAILED_CREATE_HOMEDIR);
        CASE_RETURN_STRING(LW_ERROR_PASSWORD_TOO_WEAK);
        CASE_RETURN_STRING(LW_ERROR_INVALID_SID_REVISION);
        CASE_RETURN_STRING(LW_ERROR_ACCOUNT_LOCKED);
        CASE_RETURN_STRING(LW_ERROR_ACCOUNT_DISABLED);
        CASE_RETURN_STRING(LW_ERROR_USER_CANNOT_CHANGE_PASSWD);
        CASE_RETURN_STRING(LW_ERROR_LOAD_LIBRARY_FAILED);
        CASE_RETURN_STRING(LW_ERROR_LOOKUP_SYMBOL_FAILED);
        CASE_RETURN_STRING(LW_ERROR_INVALID_EVENTLOG);
        CASE_RETURN_STRING(LW_ERROR_INVALID_CONFIG);
        CASE_RETURN_STRING(LW_ERROR_UNEXPECTED_TOKEN);
        CASE_RETURN_STRING(LW_ERROR_LDAP_NO_RECORDS_FOUND);
        CASE_RETURN_STRING(LW_ERROR_DUPLICATE_USERNAME);
        CASE_RETURN_STRING(LW_ERROR_DUPLICATE_GROUPNAME);
        CASE_RETURN_STRING(LW_ERROR_DUPLICATE_CELLNAME);
        CASE_RETURN_STRING(LW_ERROR_STRING_CONV_FAILED);
        CASE_RETURN_STRING(LW_ERROR_INVALID_ACCOUNT);
        CASE_RETURN_STRING(LW_ERROR_INVALID_PASSWORD);
        CASE_RETURN_STRING(LW_ERROR_QUERY_CREATION_FAILED);
        CASE_RETURN_STRING(LW_ERROR_NO_SUCH_OBJECT);
        CASE_RETURN_STRING(LW_ERROR_DUPLICATE_USER_OR_GROUP);
        CASE_RETURN_STRING(LW_ERROR_INVALID_KRB5_CACHE_TYPE);
        CASE_RETURN_STRING(LW_ERROR_NOT_JOINED_TO_AD);
        CASE_RETURN_STRING(LW_ERROR_FAILED_TO_SET_TIME);
        CASE_RETURN_STRING(LW_ERROR_NO_NETBIOS_NAME);
        CASE_RETURN_STRING(LW_ERROR_INVALID_NETLOGON_RESPONSE);
        CASE_RETURN_STRING(LW_ERROR_INVALID_OBJECTGUID);
        CASE_RETURN_STRING(LW_ERROR_INVALID_DOMAIN);
        CASE_RETURN_STRING(LW_ERROR_NO_DEFAULT_REALM);
        CASE_RETURN_STRING(LW_ERROR_NOT_SUPPORTED);
        CASE_RETURN_STRING(LW_ERROR_LOGON_FAILURE);
        CASE_RETURN_STRING(LW_ERROR_NO_SITE_INFORMATION);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LDAP_STRING);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LDAP_ATTR_VALUE);
        CASE_RETURN_STRING(LW_ERROR_NULL_BUFFER);
        CASE_RETURN_STRING(LW_ERROR_CLOCK_SKEW);
        CASE_RETURN_STRING(LW_ERROR_KRB5_NO_KEYS_FOUND);
        CASE_RETURN_STRING(LW_ERROR_SERVICE_NOT_AVAILABLE);
        CASE_RETURN_STRING(LW_ERROR_INVALID_SERVICE_RESPONSE);
        CASE_RETURN_STRING(LW_ERROR_NSS_ERROR);
        CASE_RETURN_STRING(LW_ERROR_AUTH_ERROR);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LDAP_DN);
        CASE_RETURN_STRING(LW_ERROR_NOT_MAPPED);
        CASE_RETURN_STRING(LW_ERROR_RPC_NETLOGON_FAILED);
        CASE_RETURN_STRING(LW_ERROR_ENUM_DOMAIN_TRUSTS_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_LSABINDING_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_OPENPOLICY_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_LSA_LOOKUPNAME2_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_SET_SESS_CREDS_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_REL_SESS_CREDS_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_CLOSEPOLICY_FAILED);
        CASE_RETURN_STRING(LW_ERROR_RPC_LSA_LOOKUPNAME2_NOT_FOUND);
        CASE_RETURN_STRING(LW_ERROR_RPC_LSA_LOOKUPNAME2_FOUND_DUPLICATES);
        CASE_RETURN_STRING(LW_ERROR_NO_TRUSTED_DOMAIN_FOUND);
        CASE_RETURN_STRING(LW_ERROR_INCOMPATIBLE_MODES_BETWEEN_TRUSTEDDOMAINS);
        CASE_RETURN_STRING(LW_ERROR_DCE_CALL_FAILED);
        CASE_RETURN_STRING(LW_ERROR_FAILED_TO_LOOKUP_DC);
        CASE_RETURN_STRING(LW_ERROR_INVALID_NSS_ARTEFACT_INFO_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_UNSUPPORTED_NSS_ARTEFACT_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_INVALID_USER_NAME);
        CASE_RETURN_STRING(LW_ERROR_INVALID_LOG_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_INVALID_METRIC_TYPE);
        CASE_RETURN_STRING(LW_ERROR_INVALID_METRIC_PACK);
        CASE_RETURN_STRING(LW_ERROR_INVALID_METRIC_INFO_LEVEL);
        CASE_RETURN_STRING(LW_ERROR_FAILED_STARTUP_PREREQUISITE_CHECK);
        CASE_RETURN_STRING(LW_ERROR_MAC_FLUSH_DS_CACHE_FAILED);
        CASE_RETURN_STRING(LW_ERROR_LSA_SERVER_UNREACHABLE);
        CASE_RETURN_STRING(LW_ERROR_INVALID_NSS_ARTEFACT_TYPE);
        CASE_RETURN_STRING(LW_ERROR_INVALID_AGENT_VERSION);
        /* End LSASS errors */
        /* Begin Netlogon errors */
        CASE_RETURN_STRING(DNS_ERROR_BAD_PACKET);
        CASE_RETURN_STRING(ERROR_BAD_CONFIGURATION);
        CASE_RETURN_STRING(ERROR_BAD_DLL_ENTRYPOINT);
        CASE_RETURN_STRING(ERROR_BAD_FORMAT);
        CASE_RETURN_STRING(ERROR_DLL_INIT_FAILED);
        CASE_RETURN_STRING(ERROR_EVENTLOG_CANT_START);
        CASE_RETURN_STRING(ERROR_ILLEGAL_CHARACTER);
        CASE_RETURN_STRING(ERROR_INTERNAL_ERROR);
        CASE_RETURN_STRING(ERROR_INVALID_PARAMETER);
        CASE_RETURN_STRING(ERROR_INVALID_TIME);
        CASE_RETURN_STRING(ERROR_NO_SUCH_DOMAIN);
        CASE_RETURN_STRING(ERROR_NOT_FOUND);
        CASE_RETURN_STRING(ERROR_NOT_JOINED);
        CASE_RETURN_STRING(ERROR_PATH_NOT_FOUND);
        CASE_RETURN_STRING(ERROR_SERVICE_DEPENDENCY_FAIL);
        CASE_RETURN_STRING(ERROR_WRITE_FAULT);
        CASE_RETURN_STRING(NERR_DCNotFound);
        /* End Netlogon errors */

        DEFAULT_RETURN_UNKNOWN_STRING();
    }
}
