#!/bin/bash

UPGRADEDIR=@MK_PREFIX@-upgrade

LOG=/var/log/likewise-open-install.log
TLOG=/tmp/LikewiseOpenTemp.txt

DAEMONS_TO_KILL="lwmgmtd lwrdrd npcmuxd likewise-open centeris.com-lwiauthd lwsmd lwregd netlogond lwiod dcerpcd eventlogd lsassd srvsvcd"

# Display to screen and log file with a blank line between entires.
log()
{
    echo $@
    echo
    echo $@ >> $LOG
    echo >> $LOG
}

# Display to screen and log file with no blank line.
_log()
{
    echo $@
    echo $@ >> $LOG
}

# Display to file.
logfile()
{
    echo $@ >> $LOG
    echo >> $LOG
}

# Execute command.
# If successful, note in log file.
# If not successful, note on screen and log file.
run()
{
    eval "$@" > $TLOG 2>&1
    err=$?
    if [ $err -eq 0 ]; then
        echo "Success: $@" >> $LOG
        cat $TLOG >> $LOG
        echo >> $LOG
    else
        _log "Error: $@ returned $err"
        _log `cat $TLOG`
        _log
    fi
    rm -f $TLOG > /dev/null 2>&1
    return $err
}

# Execute command.
# Log only to file.
run_quiet()
{
    eval "$@" > $TLOG 2>&1
    err=$?
    if [ $err -eq 0 ]; then
        echo "Success: $@" >> $LOG
    else
        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
    fi
    cat $TLOG >> $LOG
    echo >> $LOG
    rm -f $TLOG > /dev/null 2>&1
    return $err
}

# Execute command.
# If successful, note in log file.
# If not successful, note on screen and log file and then exit.
run_or_fail()
{
    eval "$@" > $TLOG 2>&1
    err=$?
    if [ $err -eq 0 ]; then
        echo "Success: $@" >> $LOG
        cat $TLOG >> $LOG
        echo >> $LOG
    else
        _log "Error: $@ returned $err  (aborting this script)"
        _log `cat $TLOG`
        _log
        rm -f $TLOG > /dev/null 2>&1
        exit 1
    fi
    rm -f $TLOG > /dev/null 2>&1
    return $err
}

ConfigureDirectoryOwners()
{
    log "Prepare common installation and dependant directories used by Likewise"

    CHOWN_0_80="/opt/ @MK_PREFIX@ /etc/ @MK_SYSCONFDIR@ /var/ /var/lib/ @LW_CACHEDIR@"
    CHOWN_0_0="/usr/ /usr/lib/"

    ETC_LW="@MK_SYSCONFDIR@"

    for f in $CHOWN_0_80; do
        case $f in
            */)
                 CHOWNFLAGS=''
                 ;;
             *)
                 CHOWNFLAGS='-R'
                 ;;
        esac

        if [ -d $f ]; then
            #log "setting $f directory owner to 0:80"
            run_or_fail "chown $CHOWNFLAGS 0:80 $f"
        else
            #log "creating $f directory and setting owner to 0:80"
            run_or_fail "mkdir $f"
            run_or_fail "chown $CHOWNFLAGS 0:80 $f"
        fi
    done

    for f in $CHOWN_0_0; do
        case $f in
            */)
                 CHOWNFLAGS=''
                 ;;
             *)
                 CHOWNFLAGS='-R'
                 ;;
        esac
        if [ -d $f ]; then
            #log "setting $f directory owner to 0:0"
            run_or_fail "chown 0:0 $f"
        else
            #log "creating $f directory and setting owner to 0:0"
            run_or_fail "mkdir $f"
            run_or_fail "chown 0:0 $f"
        fi
    done
}

wait_for_lwsm_running_status()
{
    status=1

    while [ $status -ne 0 ]; do
        @MK_BINDIR@/lwsm list > /dev/null 2>&1
        status=$?
        sleep 1
    done

    log "Service lwsmd running"
}

wait_for_service_running_status()
{
    SERVICE=$1
    status=1

    while [ $status -ne 0 ]; do
        @MK_BINDIR@/lwsm status $SERVICE > /dev/null 2>&1
        status=$?
        sleep 1
    done

    log "Service $SERVICE running"
}

configure_and_start_lwsmd()
{
    SERVICE_NAME=com.likewisesoftware.lwsmd
    SERVICE_DAEMON=/Library/LaunchDaemons/$SERVICE_NAME.plist
    SERVICE_DAEMON_INSTALL=/etc/likewise/LaunchDaemons/$SERVICE_NAME.plist

    if [ -f $SERVICE_DAEMON_INSTALL ]; then
        log "Configuring and starting lwsmd service with launchctl"
        run_or_fail "cp $SERVICE_DAEMON_INSTALL $SERVICE_DAEMON"
        run_or_fail "launchctl load $SERVICE_DAEMON"
        run_or_fail "launchctl start $SERVICE_NAME"
        wait_for_lwsm_running_status
    fi
}

enable_plugin()
{
    PLUGIN_DIR=LWDSPlugin.dsplug
    SRC_DIR=@PRIMARY_LIBDIR@
    FRAMEWORK_DIR="/System/Library/Frameworks/DirectoryService.framework/Resources/Plugins"
    LIBRARY_DS_DIR="/Library/DirectoryServices/PlugIns"

    for plugin in LWIDSPlugIn LWEDSPlugIn LWDSPlugin ; do
        path="$FRAMEWORK_DIR/${plugin}.dsplug"
        if [ -h "${path}" ]; then
            run_or_fail "rm -fv ${path}"
        fi
    done

    for plugin in LWIDSPlugIn LWEDSPlugIn LWDSPlugin ; do
        path="$LIBRARY_DS_DIR/${plugin}.dsplug"
        if [ -d "${path}" ]; then
            run_or_fail "rm -r ${path}"
        fi
    done

    # Install new plugin
    run_or_fail "mkdir -p $LIBRARY_DS_DIR"
    run_or_fail "cp -r $SRC_DIR/$PLUGIN_DIR $LIBRARY_DS_DIR/$PLUGIN_DIR"

    if [ -f /usr/bin/setfile ]; then
        run_or_fail "/usr/bin/setfile -a V /opt"
    else
        grep opt /.hidden > /dev/null
        if [ $? -ne 0 ]; then
            echo "opt" >> /.hidden
        fi
    fi

    killall DirectoryService
    sleep 5

}

enable_auth_plugin()
{
    PLUGIN_DIR=com.likewise.bundle
    SRC_DIR="@PRIMARY_LIBDIR@/SecurityAgentPlugins"
    LIBRARY_PLUGIN_DIR="/Library/Security/SecurityAgentPlugins"

    # Install auth plugin
    log "Installing auth plugin"
    mkdir -p $LIBRARY_PLUGIN_DIR
    cp -r $SRC_DIR/$PLUGIN_DIR $LIBRARY_PLUGIN_DIR/$PLUGIN_DIR

    for module in /opt/likewise/lib/AuthMechanisms/*.so
    do
        mechanism=`basename "$module" .so`
        log "Enabling auth mechanism '$mechanism'"
        run_or_fail /opt/likewise/libexec/authmechanism enable "$mechanism"
    done
}

configure_logon_message_application()
{
    /usr/bin/defaults read /Library/Preferences/loginwindow | grep 'Likewise Logon Message.app' > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        log "Configuring Likewise Logon Message application"
        defaults write /Library/Preferences/loginwindow AutoLaunchedApplicationDictionary -array-add '{ "Path" = "@MK_BINDIR@/Likewise Logon Message.app"; "Hide" = "0"; }'
    else
        log "Likewise Logon Message application already configured"
    fi
}

configure_agent()
{
    agent_name="$1"
    AGENT_PLIST=/Library/LaunchAgents/$agent_name.plist
    AGENT_PLIST_INSTALL=/etc/likewise/LaunchAgents/$agent_name.plist

    if [ -f $AGENT_PLIST_INSTALL ]; then
        #log "Installing login agent $agent_name"
        run_or_fail "cp $AGENT_PLIST_INSTALL $AGENT_PLIST"
    fi
}

import_5_0123_file()
{
    CONVERT="@MK_LIBEXECDIR@/conf2reg"
    REGIMPORT="@MK_BINDIR@/lwregshell import"

    COMMAND=$1
    SOURCE=$2
    # DEST is not necessary for some commands.
    DEST=$3

    if [ -f $SOURCE ]; then
        run_quiet "$CONVERT $COMMAND $SOURCE $DEST"
        if [ $? -ne 0 ]; then
            log "There was a problem converting $SOURCE. Please file a bug and attach $SOURCE."
            return 1
        fi

        if [ -n "$DEST" -a -f "$DEST" ]; then
            run_quiet "$REGIMPORT $DEST"
            if [ $? -ne 0 ]; then
                log "There was a problem converting $SOURCE. Please file a bug and attach $SOURCE and $DEST."
                return 1
            fi
        fi
    fi
    return 0
}

restore_5_0123_configuration()
{
    CONVERT="@MK_LIBEXECDIR@/conf2reg"

    if [ -z "$UPGRADING_FROM_5_0123" ]; then
        return 0
    fi

    import_5_0123_file "--lsass" "${UPGRADEDIR}/lsassd.conf" \
        "${UPGRADEDIR}/lsassd.conf.reg"

    import_5_0123_file "--netlogon" "${UPGRADEDIR}/netlogon.conf" \
        "${UPGRADEDIR}/netlogon.conf.reg"

    import_5_0123_file "--eventlog" "${UPGRADEDIR}/eventlogd.conf" \
        "${UPGRADEDIR}/eventlogd.conf.reg"

    import_5_0123_file "--pstore-sqlite" "${UPGRADEDIR}/pstore.db"
}

restore_6_0_configuration()
{
    if [ -z "$UPGRADING_FROM_6_0" ]; then
        return 0
    fi

    if [ -f "${UPGRADEDIR}/registry.db" ]; then
        #log "Restoring /var/lib/likewise/db/registry.db"
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/registry.db /var/lib/likewise/db/registry.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/registry.db"
    fi

    if [ -f "${UPGRADEDIR}/sam.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/sam.db /var/lib/likewise/db/sam.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/sam.db"
    fi

    if [ -f "${UPGRADEDIR}/lwi_events.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lwi_events.db /var/lib/likewise/db/lwi_events.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/lwi_events.db"
    fi

    if [ -f "${UPGRADEDIR}/lsass-adcache.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lsass-adcache.db /var/lib/likewise/db/lsass-adcache.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/lsass-adcache.db"
    fi

    if [ -f "${UPGRADEDIR}/lsass-adcache.filedb" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lsass-adcache.filedb /var/lib/likewise/db/lsass-adcache.filedb"
        run_or_fail "chmod 700 /var/lib/likewise/db/lsass-adcache.filedb"
    fi

    run_quiet "rm -r ${UPGRADEDIR}"
}

restore_6_1_configuration()
{
    if [ -z "$UPGRADING_FROM_6_1" ]; then
        return 0
    fi

    if [ -f "${UPGRADEDIR}/registry.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/registry.db /var/lib/likewise/db/registry.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/registry.db"
    fi

    if [ -f "${UPGRADEDIR}/sam.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/sam.db /var/lib/likewise/db/sam.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/sam.db"
    fi

    if [ -f "${UPGRADEDIR}/lwi_events.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lwi_events.db /var/lib/likewise/db/lwi_events.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/lwi_events.db"
    fi

    if [ -f "${UPGRADEDIR}/lsass-adcache.db" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lsass-adcache.db /var/lib/likewise/db/lsass-adcache.db"
        run_or_fail "chmod 700 /var/lib/likewise/db/lsass-adcache.db"
    fi

    if [ -f "${UPGRADEDIR}/lsass-adcache.filedb" ]; then
        run_or_fail "mkdir -p /var/lib/likewise/db"
        run_or_fail "chmod 700 /var/lib/likewise/db"
        run_or_fail "chown 0:80 /var/lib/likewise/db"

        run_or_fail "cp ${UPGRADEDIR}/lsass-adcache.filedb /var/lib/likewise/db/lsass-adcache.filedb"
        run_or_fail "chmod 700 /var/lib/likewise/db/lsass-adcache.filedb"
    fi


    run_quiet "rm -r ${UPGRADEDIR}"
}

import_registry_configurations()
{
    REGIMPORT='@MK_BINDIR@/lwregshell import'

    log "Importing registry..."
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/dcerpcd.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/eventlogd.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/lsassd.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/privileges.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/accounts.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/lwiod.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/lwreg.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/netlogond.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/rdr.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/npfs.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/srv.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/pvfs.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/srvsvcd.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/nfs.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/reapsysl.reg"
    run_or_fail "$REGIMPORT @LW_CONFIGDIR@/lwdsplugin.reg"
}

determine_upgrade_type()
{
    PRESERVEDVERSIONFILE="${UPGRADEDIR}/VERSION"

    if [ -f $PRESERVEDVERSIONFILE ]; then
        run_or_fail "cat $PRESERVEDVERSIONFILE"
        if [ -n "`grep '^VERSION=5.0' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_5_0123=1
            log "Upgrading from Likewise Identity Services Open 5.0"
        elif [ -n "`grep '^VERSION=5.1' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_5_0123=1
            log "Upgrading from Likewise Identity Services Open 5.1."
        elif [ -n "`grep '^VERSION=5.2' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_5_0123=1
            log "Upgrading from Likewise Identity Services Open 5.2."
        elif [ -n "`grep '^VERSION=5.3' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_5_0123=1
            log "Upgrading from Likewise Identity Services Open 5.3."
        elif [ -n "`grep '^VERSION=6.0' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_6_0=1
            log "Upgrading from Likewise Open 6.0."
        elif [ -n "`grep '^VERSION=6.1' $PRESERVEDVERSIONFILE`" ]; then
            UPGRADING_FROM_6_1=1
            log "Upgrading from Likewise Open 6.1."
        fi
    fi
}

import_5_0123_file()
{
    CONVERT="@MK_LIBEXECDIR@/conf2reg"
    REGIMPORT="@MK_BINDIR@/lwregshell import"

    COMMAND=$1
    SOURCE=$2
    # DEST is not necessary for some commands.
    DEST=$3

    if [ -f $SOURCE ]; then
        run_quiet "$CONVERT $COMMAND $SOURCE $DEST"
        if [ $? -ne 0 ]; then
            log "There was a problem converting $SOURCE. Please file a bug and attach $SOURCE."
            return 1
        fi

        if [ -n "$DEST" -a -f "$DEST" ]; then
            run_quiet "$REGIMPORT $DEST"
            if [ $? -ne 0 ]; then
                log "There was a problem converting $SOURCE. Please file a bug and attach $SOURCE and $DEST."
                return 1
            fi
        fi
    fi
    return 0
}

restore_5_0123_configuration()
{
    CONVERT="@MK_LIBEXECDIR@/conf2reg"

    if [ -z "$UPGRADING_FROM_5_0123" ]; then
        return 0
    fi

    import_5_0123_file "--lsass" "${UPGRADEDIR}/lsassd.conf" \
        "${UPGRADEDIR}/lsassd.conf.reg"

    import_5_0123_file "--netlogon" "${UPGRADEDIR}/netlogon.conf" \
        "${UPGRADEDIR}/netlogon.conf.reg"

    import_5_0123_file "--eventlog" "${UPGRADEDIR}/eventlogd.conf" \
        "${UPGRADEDIR}/eventlogd.conf.reg"

    import_5_0123_file "--pstore-sqlite" "${UPGRADEDIR}/pstore.db"
}

relocate_domain_separator()
{
    DomainSeparator=`@MK_BINDIR@/lwregshell list_values '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' | grep DomainSeparator | sed -e 's/ *[^ ]\+[ ]\+[^ ]\+[ ]\+"\([^ ]*\)"$/\1/'`

    if [ -n "${DomainSeparator}" ]; then
        if [ "$DomainSeparator" = "\\\\" ]; then
            DomainSeparator="\\"
        fi

        run_quiet @MK_BINDIR@/lwregshell set_value '[HKEY_THIS_MACHINE\Services\lsass\Parameters]' 'DomainSeparator' "$DomainSeparator"
    fi
}

relocate_space_replacement()
{
    SpaceReplacement=`@MK_BINDIR@/lwregshell list_values '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' | grep SpaceReplacement | sed -e 's/ *[^ ]\+[ ]\+[^ ]\+[ ]\+"\([^ ]*\)"$/\1/'`

    if [ -n "${SpaceReplacement}" ]; then
        run_quiet @MK_BINDIR@/lwregshell set_value '[HKEY_THIS_MACHINE\Services\lsass\Parameters]' 'SpaceReplacement' "$SpaceReplacement"
    fi
}

fix_60_registry()
{
    REGCLEANUP="@MK_BINDIR@/lwregshell cleanup"

    if [ -z "$UPGRADING_FROM_6_0" ]; then
        return 0
    fi

    # Migrate pstore entries from default to joined domain
    run "@MK_LIBEXECDIR@/regupgr61.sh --install"

    # Migrate some other entries
    relocate_domain_separator
    relocate_space_replacement

    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/dcerpcd.reg"
    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/eventlogd.reg"
    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/lsassd.reg"
    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/lwiod.reg"
    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/lwreg.reg"
    run_or_fail "${REGCLEANUP} @LW_CONFIGDIR@/netlogond.reg"
}

switch_to_open_provider()
{
    _value='[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]'
    _path='@PRIMARY_LIBDIR@/liblsass_auth_provider_ad_open.so'

    run_quiet "@MK_BINDIR@/lwregshell set_value $_value Path $_path"
}

##
## Main
##

log "Finalizing Likewise installation process"

ConfigureDirectoryOwners

#
# Upgrading OS X (at least 10.6 to 10.7) deletes /var/lib/likewise.
# So on OS X we actually use /opt/likewise/var and put in a symlink
# back to /var/lib/likewise.  On every boot we make sure the symlink is
# still there before starting our daemons.
#
log "Moving /var/lib/likewise to /opt/likewise/var."
run_or_fail cp -rp /var/lib/likewise /opt/likewise/var
run_or_fail rm -rf /var/lib/likewise
run_or_fail ln -s /opt/likewise/var /var/lib/likewise

determine_upgrade_type

restore_6_0_configuration

restore_6_1_configuration

run_or_fail "@MK_SBINDIR@/lwsmd --start-as-daemon --loglevel debug"

restore_5_0123_configuration

import_registry_configurations

fix_60_registry

switch_to_open_provider

run_or_fail "@MK_BINDIR@/lwsm shutdown"

configure_and_start_lwsmd

run "@MK_BINDIR@/domainjoin-cli configure --enable pam"

# Configure Likewise DS plugin
enable_plugin

# Configure Likewise Auth plugin
enable_auth_plugin

# Add Likewise DS Plugin to Search list
echo "Adding DS plugin to search list"
run "/usr/bin/dscl /Search -create / SearchPolicy CSPSearchPath"
run "/usr/bin/dscl /Search -append / CSPSearchPath '/Likewise - Active Directory'"

# Create Global Login Item entry for Likewise Logon Message.app
# to display licensing and password expiration warning messages on
# user logon activity.
configure_logon_message_application

# Add the ticketcopy login agent
configure_agent com.likewisesoftware.ticketcopy

# Add Likewise Utilities folder to Applications location in Finder. Shortcut
# the Likewise Domain Join application to here.
if [ -d '/Applications/Likewise Utilities' ]; then
    _log "Likewise Utilities folder already exists"
else
    run "mkdir -p '/Applications/Likewise Utilities'"
fi

if [ -f '/Applications/Likewise Utilities/Likewise Domain Join.app' ]; then
    _log "Likewise Domain Join application already created in utilities folder"
else
    run "ln -s '@MK_BINDIR@/Likewise Domain Join.app' '/Applications/Likewise Utilities/Likewise Domain Join.app'"
fi

domain=`@MK_BINDIR@/lw-lsa ad-get-machine account 2>/dev/null | grep '  DNS Domain Name: ' | sed -e 's/  DNS Domain Name: //'`

if [ -n "$UPGRADING_FROM_5_0123" ]; then
    log "Likewise Identity Services Open 5.X has been successfully upgraded."
fi

if [ -n "$UPGRADING_FROM_6_0" ]; then
    log "Likewise Open 6.0 has been successfully upgraded."
fi

if [ -z "$domain" ]; then
    _log ""
    _log "Use the domainjoin-cli program to join your computer to an Active "
    _log "Directory domain which will enable logons to your system with Active Directory "
    _log "user accounts."
else
    _log ""
    _log "Your computer is joined to $domain"
fi

exit 0
