[
uuid(12345778-1234-abcd-ef00-0123456789ab),
version(0.0),
pointer_default(unique)
]
interface lsa
{
cpp_quote("#ifdef DCERPC_STUB_BUILD")

#include <lw/security-types.h>
#include <lwrpc/types.h>
#include <lwrpc/unistrdef.h>
#include <lwrpc/lsadefs.h>


    /* LsaPolicyInformation union returned from LsaQueryInfoPolicy */
    typedef [switch_type(UINT16)] union lsa_policy_information {
        [case(LSA_POLICY_INFO_AUDIT_LOG)]        AuditLogInfo        audit_log;
        [case(LSA_POLICY_INFO_AUDIT_EVENTS)]     AuditEventsInfo     audit_events;
        [case(LSA_POLICY_INFO_DOMAIN)]           LsaDomainInfo       domain;
        [case(LSA_POLICY_INFO_PD)]               PDAccountInfo       pd;
        [case(LSA_POLICY_INFO_ACCOUNT_DOMAIN)]   LsaDomainInfo       account_domain;
        [case(LSA_POLICY_INFO_ROLE)]             ServerRole          role;
        [case(LSA_POLICY_INFO_REPLICA)]          ReplicaSourceInfo   replica;
        [case(LSA_POLICY_INFO_QUOTA)]            DefaultQuotaInfo    quota;
        [case(LSA_POLICY_INFO_DB)]               ModificationInfo    db;
        [case(LSA_POLICY_INFO_AUDIT_FULL_SET)]   AuditFullSetInfo    audit_set;
        [case(LSA_POLICY_INFO_AUDIT_FULL_QUERY)] AuditFullQueryInfo  audit_query;
        [case(LSA_POLICY_INFO_DNS)]              DnsDomainInfo       dns;
    } LsaPolicyInformation;


cpp_quote("#endif")

	/* function 0x00 */
    NTSTATUS __LsaClose(
        [in] POLICY_HANDLE hIn,
        [out] POLICY_HANDLE *hOut
        );

    NTSTATUS _lsa_Function01();
    NTSTATUS _lsa_Function02();
    NTSTATUS _lsa_Function03();
    NTSTATUS _lsa_Function04();
    NTSTATUS _lsa_Function05();
    NTSTATUS _lsa_Function06();

	/* function 0x07 */
    NTSTATUS __LsaQueryInfoPolicy(
        [in] POLICY_HANDLE hPolicy,
        [in] UINT16 level,
        [out,switch_is(level)] LsaPolicyInformation **info
        );

    NTSTATUS _lsa_Function08();
    NTSTATUS _lsa_Function09();
    NTSTATUS _lsa_Function0a();
    NTSTATUS _lsa_Function0b();
    NTSTATUS _lsa_Function0c();
    NTSTATUS _lsa_Function0d();

	/* function 0x0e */
    NTSTATUS __LsaLookupNames(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UnicodeString *names,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count
        );

	/* function 0x0f */
    NTSTATUS __LsaLookupSids(
        [in] POLICY_HANDLE hPolicy,
        [in] SidArray *sids,
        [out] RefDomainList **domains,
        [in,out] TranslatedNameArray *names,
        [in] UINT16 level,
        [in,out] UINT32 *count
        );

    NTSTATUS _lsa_Function10();
    NTSTATUS _lsa_Function11();
    NTSTATUS _lsa_Function12();
    NTSTATUS _lsa_Function13();
    NTSTATUS _lsa_Function14();
    NTSTATUS _lsa_Function15();
    NTSTATUS _lsa_Function16();
    NTSTATUS _lsa_Function17();
    NTSTATUS _lsa_Function18();
    NTSTATUS _lsa_Function19();
    NTSTATUS _lsa_Function1a();
    NTSTATUS _lsa_Function1b();
    NTSTATUS _lsa_Function1c();
    NTSTATUS _lsa_Function1d();
    NTSTATUS _lsa_Function1e();
    NTSTATUS _lsa_Function1f();
    NTSTATUS _lsa_Function20();
    NTSTATUS _lsa_Function21();
    NTSTATUS _lsa_Function22();
    NTSTATUS _lsa_Function23();
    NTSTATUS _lsa_Function24();
    NTSTATUS _lsa_Function25();
    NTSTATUS _lsa_Function26();
    NTSTATUS _lsa_Function27();
    NTSTATUS _lsa_Function28();
    NTSTATUS _lsa_Function29();
    NTSTATUS _lsa_Function2a();
    NTSTATUS _lsa_Function2b();

	/* function 0x2c */
    NTSTATUS __LsaOpenPolicy2(
        [in,string,unique] wchar16_t *system_name,
        [in] ObjectAttribute *attrib,
        [in] UINT32 access_mask,
        [out] POLICY_HANDLE *hPolicy
        );

    NTSTATUS _lsa_Function2d();

	/* function 0x2e */
    NTSTATUS __LsaQueryInfoPolicy2(
        [in] POLICY_HANDLE hPolicy,
        [in] UINT16 level,
        [out,switch_is(level)] LsaPolicyInformation **info
        );

    NTSTATUS _lsa_Function2f();
    NTSTATUS _lsa_Function30();
    NTSTATUS _lsa_Function31();
    NTSTATUS _lsa_Function32();
    NTSTATUS _lsa_Function33();
    NTSTATUS _lsa_Function34();
    NTSTATUS _lsa_Function35();
    NTSTATUS _lsa_Function36();
    NTSTATUS _lsa_Function37();
    NTSTATUS _lsa_Function38();

    /* function 0x39 */
    NTSTATUS __LsaLookupSids2(
        [in] POLICY_HANDLE hPolicy,
        [in] SidArray *sids,
        [out] RefDomainList **domains,
        [in,out] TranslatedNameArray2 *names,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );

	/* function 0x3a */
    NTSTATUS __LsaLookupNames2(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UnicodeStringEx *names,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray2 *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );

    NTSTATUS _lsa_Function3b();
    NTSTATUS _lsa_Function3c();
    NTSTATUS _lsa_Function3d();
    NTSTATUS _lsa_Function3e();
    NTSTATUS _lsa_Function3f();
    NTSTATUS _lsa_Function40();
    NTSTATUS _lsa_Function41();
    NTSTATUS _lsa_Function42();
    NTSTATUS _lsa_Function43();

    /* function 0x44 */
    NTSTATUS __LsaLookupNames3(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UnicodeStringEx *names,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray3 *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );
}


/*
local variables:
mode: c
c-basic-offset: 4
indent-tabs-mode: nil
tab-width: 4
end:
*/
