javac -classpath ..\..\lib\xerces.jar;. OpenSoapConstants.java
javac -classpath ..\..\lib\xerces.jar;. XMLWriter.java
javac -classpath ..\..\lib\xerces.jar;. OpenSoapException.java
javac -classpath ..\..\lib\xerces.jar;. OpenSoapEnvelope.java
javac -classpath ..\..\lib\xerces.jar;. OpenSoapRequest.java
javac -classpath ..\..\lib\xerces.jar;. CalcClientRequest.java
javac -classpath ..\..\lib\xerces.jar;. CalcClientResult.java
javac -classpath ..\..\lib\xerces.jar;. CalcClientPanel.java
javac -classpath ..\..\lib\xerces.jar;. CalcClient.java
