#ifndef __GPADEFINES_H__
#define __GPADEFINES_H__

#define MAX_TOKEN_LENGTH 512

#define MAX_SOCKET_STALETIME 30

#define GPO_DEFAULT_POLL_TIMEOUT_SECS (30 * 60)
#define GPO_MIN_POLL_TIMEOUT_SECS     (60)
#define GPO_MAX_POLL_TIMEOUT_SECS     (24 * 60 * 60)

#define KRB5CCENVVAR "KRB5CCNAME"

#define DC_PREFIX "dc="

#endif /* __GPADEFINES_H__ */


