#!/bin/sh

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:PREFIX_DIR/lib
export LD_LIBRARY_PATH

if test -x PREFIX_DIR/bin/refreshgpo; then
   exec PREFIX_DIR/bin/refreshgpo $@
else
   echo "Error: Failed to find PREFIX_DIR/bin/refreshgpo"
   exit 1
fi

