/*
 * 
 * (c) Copyright 1989 OPEN SOFTWARE FOUNDATION, INC.
 * (c) Copyright 1989 HEWLETT-PACKARD COMPANY
 * (c) Copyright 1989 DIGITAL EQUIPMENT CORPORATION
 * To anyone who acknowledges that this file is provided "AS IS"
 * without any express or implied warranty:
 *                 permission to use, copy, modify, and distribute this
 * file for any purpose is hereby granted without fee, provided that
 * the above copyright notices and this notice appears in all source
 * code copies, and that none of the names of Open Software
 * Foundation, Inc., Hewlett-Packard Company, or Digital Equipment
 * Corporation be used in advertising or publicity pertaining to
 * distribution of the software without specific, written prior
 * permission.  Neither Open Software Foundation, Inc., Hewlett-
 * Packard Company, nor Digital Equipment Corporation makes any
 * representations about the suitability of this software for any
 * purpose.
 * 
 */
/*
 */
/*
**
**  NAME
**
**      perfg.idl
**
**  FACILITY:
**
**      Remote Procedure Call (RPC) 
**
**  ABSTRACT:
**
**  Performance and system execiser interface auxiliary interface.
**  This interface is generic.
**
**
*/

[uuid(3C4D1F3F-7000-0000-0D00-013422000000),
    version(1),
    endpoint("ncadg_ip_udp:[2001]", "ncadg_dds:[18]", 
             "ncacn_ip_tcp:[2001]", "ncacn_dnet_nsp:[perf_server]")
]
interface perfg
{

void perfg_op1
(
    [in]        handle_t            handle,
    [in]        unsigned long       n,
    [out]       unsigned long       *x
);

void perfg_op2
(
    [in]        handle_t            handle,
    [in]        unsigned long       n,
    [out]       unsigned long       *x
);

}
