#ifndef __LWIMACIFACE_ERRCODES_H__
#define __LWIMACIFACE_ERRCODES_H_

/* Mac GP setting CSE error codes*/
#define GP_MAC_ITF_FAILED_OPEN_FILE                1
#define GP_MAC_ITF_FAILED_CREATE_STREAM            2
#define GP_MAC_ITF_FAILED_OPEN_STREAM              3
#define GP_MAC_ITF_FAILED_CREATE_PLIST             4
#define GP_MAC_ITF_FAILED_CREATE_FILE              5
#define GP_MAC_ITF_FAILED_WRITE_PLIST              6
#define GP_MAC_ITF_FAILED_MOVE_FILE                7
#define GP_MAC_ITF_FAILED_WRONG_FORMAT             8
#define GP_MAC_ITF_FAILED_CREATE_DICTIONARY        9
#define GP_MAC_ITF_FAILED_CONVERT_STRING_ENCODING 10
#define GP_MAC_ITF_FAILED_QUERY_DICTIONARY        11
#define GP_MAC_ITF_FAILED_SETTING_UPDATE          12
#define GP_MAC_ITF_FAILED_GET_PLIST_ENTRY         13
#define GP_MAC_ITF_FAILED_STRING_OPERATION        14
#define GP_MAC_ITF_SETTING_NOT_SUPPORTED          15

#endif

