#ifndef __LWISETTINGS_H__
#define __LWISETTINGS_H__

#define LWISETTINGS_GUID "{0EED766B-2404-46A6-A6B6-F8971164A920}"

#define LWI_CSE_PID_DIR "/var/run"
#define LWI_CSE_AUTH_DAEMON_NAME "likewise-winbindd"
#define LWI_CSE_AUTH_PID_FILE LWI_CSE_PID_DIR "/" LWI_CSE_AUTH_DAEMON_NAME ".pid"

#define  LWIAUTHD_FILEPATH                      "/etc/samba/lwiauthd.conf"
#define  LWIAUTHD_FILEPATH_GP                   "/etc/samba/lwiauthd.conf.gp"
#define  LWIAUTHD_WINBIND_POLICY_FILEPATH       "/etc/samba/lwiauthd.policy.conf"
#define  LWIAUTHD_WINBIND_POLICY_FILEPATH_GP    "/etc/samba/lwiauthd.policy.conf.gp"
#define  LWIAUTHD_LSASS_POLICY_FILEPATH         "/etc/likewise/lsassd.conf"
#define  LWIAUTHD_LSASS_POLICY_FILEPATH_GP      "/etc/likewise/lsassd.conf.gp"
#define  LWIAUTHD_LSASS_POLICY_FILEPATH_OLD     "/etc/likewise/lsassd.conf.lwidentity-gp.orig"
#define  LWILOGON_FILEPATH                      "/etc/security/pam_lwidentity.conf"
#define  LWILOGON_FILEPATH_GP                   "/etc/security/pam_lwidentity.conf.gp"

#define  LWIKRB5_FILEPATH                       "/etc/krb5.conf"
#define  LWIKRB5_FILEPATH_GP                    "/etc/krb5.conf.gp"
#define  LWIKRB5_BAK_FILEPATH                   "/etc/krb5.conf.lwidentity.bak"

#define  LWICONF_FILE_HEADER  "## NOTE:\n"\
                              "## This file is managed by Likewise Enterprise Group Policy.\n"\
                              "## Do not edit this file directly.\n"\
                              "## To make local modifications modify the master file\n"\
                              "## %s\n"\
                              "## and run /opt/likewise/bin/gporefresh."

CENTERROR
SignalLwiauthd();

#endif /* __LWISETTINGS_H__ */

