#ifndef __FSTAB_H__
#define __FSTAB_H__

#define  LWIFSTAB_FILE_HEADER "## NOTE:\n"\
                              "## This file is managed by Likewise Enterprise Group Policy.\n"\
                              "## Do not edit this file directly.\n"\
                              "## To make local modifications modify the master file\n"\
                              "## %s\n"\
                              "## and run /opt/likewise/bin/gporefresh."

#define LWIFSTAB_CREDENTIALS_FILEPATH   CACHEDIR ""

#if defined(__LWI_AIX__)

#define  LWIFSTAB_FILEPATH              "/etc/filesystems"
#define  LWIFSTAB_FILENAME              "filesystems"
#define  LWIFSTAB_FILEPATH_GP           "/etc/filesystems.gp"
#define  LWIFSTAB_CREDENTIALS_FILENAME  "likewise_filesystems_cifs_"
#define  LWIFSTAB_BACKUP_FILEPATH       "/etc/filesystems.lwidentity.orig"

#elif defined(__LWI_SOLARIS__)

#define  LWIFSTAB_FILEPATH              "/etc/vfstab"
#define  LWIFSTAB_FILENAME              "vfstab"
#define  LWIFSTAB_FILEPATH_GP           "/etc/vfstab.gp"
#define  LWIFSTAB_CREDENTIALS_FILENAME  "likewise_vfstab_cifs_"
#define  LWIFSTAB_BACKUP_FILEPATH       "/etc/vfstab.lwidentity.orig"
#define  LWIFSTAB_FIELD_CNT             7

#else

#define  LWIFSTAB_FILEPATH              "/etc/fstab"
#define  LWIFSTAB_FILENAME              "fstab"
#define  LWIFSTAB_FILEPATH_GP           "/etc/fstab.gp"
#define  LWIFSTAB_CREDENTIALS_FILENAME  "likewise_fstab_cifs_"
#define  LWIFSTAB_BACKUP_FILEPATH       "/etc/fstab.lwidentity.orig"
#define  LWIFSTAB_FIELD_CNT             6

#endif


#define LWI_FSTAB_ENTRY         "fstab-entry"
#define LWI_FSTAB_MOUNT_VOL     "mount-volume"
#define LWI_FSTAB_MOUNT_PT      "name"
#define LWI_FSTAB_FSTYPE        "fstype"

#define LWI_FSTAB_USERNAME      "username"
#define LWI_FSTAB_PASSWORD      "password"
#define LWI_FSTAB_UID           "uid"
#define LWI_FSTAB_GID           "gid"
#define LWI_FSTAB_RESUID        "resuid"
#define LWI_FSTAB_RESGID        "resgid"
#define LWI_FSTAB_RO            "ro"
#define LWI_FSTAB_MOUNT_VOL_OPT "MountVolumeOption"
#define LWI_FSTAB_FILETYPE      "cifs"

/* valid types */
#define LWI_ATTR_TYPE_STRING    "string"
#define LWI_ATTR_TYPE_BOOL      "bool"

#define LWIFSTAB_CLIENT_GUID    "{36C20771-2724-4ee3-B1B0-36A396CDA5E3}"
#define LWIFSTAB_ITEM_GUID      "{EF31B0C1-5DF1-4455-9C71-C83E729EC70B}"

#define BUFFER_SIZE             1024
#define STATIC_PATH_BUFFER_SIZE 256

typedef enum {
    FSTAB_MOUNTVOLUME = 0,
#if defined(__LWI_SOLARIS__)
    FSTAB_DEVICETOFSCK,
#endif
    FSTAB_MOUNTPOINT,
    FSTAB_FILETYPE,
#if defined(__LWI_SOLARIS__)
    FSTAB_FSCKPASS,
    FSTAB_MOUNTATBOOT,
#endif
    FSTAB_MOUNTOPTIONS,
    FSTAB_FREQUENCY,
    FSTAB_PASSCODE
} FSTabColumn;

typedef struct _FSTAB_OBJECT {
#if defined(__LWI_AIX__)
    PSTR pszSectionName;
    PSTR pszAccount;
    PSTR pszBoot;
    PSTR pszMount;
    PSTR pszNodeName;
    PSTR pszSize;
    PSTR pszType;
    PSTR pszLog;
    PSTR pszFree;
#endif
    PSTR pszMountVol;
    PSTR pszMountPt;
    PSTR pszFileType;
    PSTR pszMountOptions;
#if !defined(__LWI_SOLARIS__) || !defined(__LWI_AIX__)
    PSTR pszFrequency;
#endif
#if defined(__LWI_SOLARIS__)
    PSTR pszDeviceToFsck;
    PSTR pszFsckPass;
    PSTR pszMountAtBoot;
#else
    PSTR pszPassCode;
#endif
    struct _FSTAB_OBJECT *pNext;
} FSTAB_OBJECT, *PFSTAB_OBJECT;

typedef struct _FSTAB_GPO_OBJECT {
    PSTR pszMountPt;
    PSTR pszDisplayName;
    PSTR pszGPOGUID;
    struct _FSTAB_GPO_OBJECT *pNext;
} FSTAB_GPO_OBJECT, *PFSTAB_GPO_OBJECT;

#endif // __FSTAB_H__
