#! /bin/sh

# Do the Solaris Dance:
if [ ! -d ~root ]  ; then
    exec /usr/xpg4/bin/sh $0 "$@" 
fi

set -e

. ${srcdir}/common

set -x 
# expect cflags from requires-test and public-dep
ARGS="--cflags requires-test"
RESULT="-I/requires-test/include -I/private-dep/include -I/public-dep/include"
run_test

# still expect those cflags for static linking case
ARGS="--static --cflags requires-test"
RESULT="-I/requires-test/include -I/private-dep/include -I/public-dep/include"
run_test

# expect libs for just requires-test and public-dep
ARGS="--libs requires-test"
RESULT="-L/requires-test/lib -L/public-dep/lib -lrequires-test -lpublic-dep"
run_test

# expect libs for requires-test, public-dep and private-dep in static case
ARGS="--static --libs requires-test"
RESULT="-L/requires-test/lib -L/private-dep/lib -L/public-dep/lib -lrequires-test -lprivate-dep -lpublic-dep"
run_test


