#! /bin/sh

# Do the Solaris Dance:
if [ ! -d ~root ]  ; then
    exec /usr/xpg4/bin/sh $0 "$@" 
fi

set -e

. ${srcdir}/common

ARGS="--define-variable=includedir=/includedir/ --cflags simple"
RESULT="-I/includedir/"

run_test
