#include <compat/dcerpc.idl.include>

[ uuid(db7e03ba-5bdb-11dc-9f61-00023f108d6c),
  version(1.0),
  pointer_default(ptr)
]

interface echon {

  boolean ReplyBack(	
	[in] handle_t            	h,
	[in] unsigned32             	in_num,
	[out, ref] unsigned32* 	      	out_num,
	[out, ref] error_status_t *	status
	);
}
