#ifndef __LWISYSLOG_POLICY_H__
#define __LWISYSLOG_POLICY_H__

#define LWISYSLOG_CLIENT_GUID "{0D18828D-E7DA-434c-A537-8AF8122E2602}"
#define LWISYSLOG_ITEM_GUID   "{B63633DC-749A-486c-90F2-41CAC01779CB}"
#define LWISYSLOG_PLAYGROUND  CACHEDIR "/systemfiles/"

#define LWISYSLOG_TEMP_FILE                             "/etc/syslog.conf.CENTERIS_TEMP"
#define LWISYSLOG_CONF_FILE                             "/etc/syslog.conf"
#define LWISYSLOG_CONF_FILE_ORIGINAL                    "/etc/syslog.conf.lwidentity.orig"
#define LWISYSLOG_CONF_FILE_BACKUP                      "/etc/syslog.conf.old"

#define LWIRSYSLOG_TEMP_FILE                            "/etc/rsyslog.conf.CENTERIS_TEMP"
#define LWIRSYSLOG_CONF_FILE                            "/etc/rsyslog.conf"
#define LWIRSYSLOG_CONF_FILE_ORIGINAL                   "/etc/rsyslog.conf.lwidentity.orig"
#define LWIRSYSLOG_CONF_FILE_BACKUP                     "/etc/rsyslog.conf.old"
#define LWIRSYSLOG_CONF_MODULE_HEADER \
				                  "#### MODULES ####\n\n" \
				                  "$ModLoad imuxsock.so    # provides support for local system logging (e.g. via logger command)\n" \
				                  "$ModLoad imklog.so      # provides kernel logging support (previously done by rklogd)\n\n" \
                                  "#### GLOBAL DIRECTIVES ####\n\n"\
                                  "# Use default timestamp format\n"\
                                  "$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat\n\n"



#define LWISYSLOG_CONF_HEADER \
                                "# This file is automatically generated by the Likewise\n" \
                                "# Enterprise group policy agent.  Do not edit it\n" \
                                "# by hand or your changes may be lost.\n\n"

#define ITER_KEY(iter) (((PGPASHASH_PAIR)(iter->data))->key)
#define ITER_VALUE(iter) (((PGPASHASH_PAIR)(iter->data))->value)

#define LWISYSLOG_NG            "/etc/syslog-ng"
#define APPARMOR_DIR            "/etc/apparmor.d"
#define APPARMOR_NG_FILE        "/etc/apparmor.d/sbin.syslog-ng"
#define APPARMOR_NG_FILE_GP     "/etc/apparmor.d/sbin.syslog-ng.gp"
#define LWISYSLOG_NG_OPTIONS    "options { long_hostnames(off); sync(0); perm(0640); stats(3600); };"
#define LWISYSLOG_NG_TEMP_FILE  "/etc/syslog-ng/syslog-ng.conf.CENTERIS_TEMP"
#define LWISYSLOG_NG_CONF_FILE  "/etc/syslog-ng/syslog-ng.conf"

#define LWISYSLOG_NG_CONF_FILE_ORIGINAL "/etc/syslog-ng/syslog-ng.conf.lwidentity.orig"
#define LWISYSLOG_NG_CONF_FILE_BACKUP "/etc/syslog-ng/syslog-ng.conf.old"
#define SELINUX_DIRECTORY  "/etc/selinux/"

#define STATIC_PATH_BUFFER_SIZE 256
#define FILEREAD_BUFSIZE 1024 

static const DWORD BUFSIZE = 4096;
static const PSTR GP_DIRECTORY     = CACHEDIR "/";
static const PSTR SYSVOL_PATH  = "\\Machine\\Centeris\\Identity\\";

typedef struct _SYSLOGNODE
{
    PSTR pszKey;
    PSTR pszValue;
    struct _SYSLOGNODE *pNext;
}SYSLOGNODE, *PSYSLOGNODE;


CENTERROR
ProcessSyslogGroupPolicy(
    DWORD dwFlags,
    PGPUSER pUser,
    PGROUP_POLICY_OBJECT pGPOModifiedList,
    PGROUP_POLICY_OBJECT pGPODeletedList
    );

CENTERROR
ResetSyslogGroupPolicy(
    PGPUSER pUser
    );
 
CENTERROR
GetFileHandle(
    PSTR SyslogTempFile,
    BOOLEAN fUseNG,
    FILE**  ppHandle
    );

#endif /* __LWISYSLOG_POLICY_H__ */
