/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

#include "mount3.h"

bool_t
xdr_empty_proc_body (XDR *xdrs, empty_proc_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getattr3_proc_call_body (XDR *xdrs, getattr3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_GETATTR3args (xdrs, &objp->agrs))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_setattr3_proc_call_body (XDR *xdrs, setattr3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_SETATTR3args (xdrs, &objp->agrs))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lookup3_proc_call_body (XDR *xdrs, lookup3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_LOOKUP3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access3_proc_call_body (XDR *xdrs, access3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_ACCESS3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readlink3_proc_call_body (XDR *xdrs, readlink3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_READLINK3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read3_proc_call_body (XDR *xdrs, read3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_READ3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write3_proc_call_body (XDR *xdrs, write3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_WRITE3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_create3_proc_call_body (XDR *xdrs, create3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_CREATE3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mkdir3_proc_call_body (XDR *xdrs, mkdir3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_MKDIR3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_symlink3_proc_call_body (XDR *xdrs, symlink3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_SYMLINK3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mknod3_proc_call_body (XDR *xdrs, mknod3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_MKNOD3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_remove3_proc_call_body (XDR *xdrs, remove3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_REMOVE3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rmdir3_proc_call_body (XDR *xdrs, rmdir3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_RMDIR3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rename3_proc_call_body (XDR *xdrs, rename3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_RENAME3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_link3_proc_call_body (XDR *xdrs, link3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_LINK3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdir3_proc_call_body (XDR *xdrs, readdir3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_READDIR3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdirplus3_proc_call_body (XDR *xdrs, readdirplus3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_READDIRPLUS3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fsstat3_proc_call_body (XDR *xdrs, fsstat3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_FSSTAT3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fsinfo3_proc_call_body (XDR *xdrs, fsinfo3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_FSINFO3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pathconf3_proc_call_body (XDR *xdrs, pathconf3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_PATHCONF3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commit3_proc_call_body (XDR *xdrs, commit3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_COMMIT3args (xdrs, &objp->args))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfsv3_call_body (XDR *xdrs, nfsv3_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	switch (objp->proc) {
	case NFSPROC3_NULL:
		 if (!xdr_empty_proc_body (xdrs, &objp->nfsv3_call_body_u.null_body))
			 return FALSE;
		break;
	case NFSPROC3_GETATTR:
		 if (!xdr_getattr3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.getattr_body))
			 return FALSE;
		break;
	case NFSPROC3_SETATTR:
		 if (!xdr_setattr3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.setattr_body))
			 return FALSE;
		break;
	case NFSPROC3_LOOKUP:
		 if (!xdr_lookup3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.lookup_body))
			 return FALSE;
		break;
	case NFSPROC3_ACCESS:
		 if (!xdr_access3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.access_body))
			 return FALSE;
		break;
	case NFSPROC3_READLINK:
		 if (!xdr_readlink3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.readlink_body))
			 return FALSE;
		break;
	case NFSPROC3_READ:
		 if (!xdr_read3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.read_body))
			 return FALSE;
		break;
	case NFSPROC3_WRITE:
		 if (!xdr_write3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.write_body))
			 return FALSE;
		break;
	case NFSPROC3_CREATE:
		 if (!xdr_create3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.create_body))
			 return FALSE;
		break;
	case NFSPROC3_MKDIR:
		 if (!xdr_mkdir3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.mkdir_body))
			 return FALSE;
		break;
	case NFSPROC3_SYMLINK:
		 if (!xdr_symlink3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.symlink_body))
			 return FALSE;
		break;
	case NFSPROC3_MKNOD:
		 if (!xdr_mknod3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.mknod_body))
			 return FALSE;
		break;
	case NFSPROC3_REMOVE:
		 if (!xdr_remove3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.remove_body))
			 return FALSE;
		break;
	case NFSPROC3_RMDIR:
		 if (!xdr_rmdir3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.rmdir_body))
			 return FALSE;
		break;
	case NFSPROC3_RENAME:
		 if (!xdr_rename3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.rename_body))
			 return FALSE;
		break;
	case NFSPROC3_LINK:
		 if (!xdr_link3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.link_body))
			 return FALSE;
		break;
	case NFSPROC3_READDIR:
		 if (!xdr_readdir3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.readdir_body))
			 return FALSE;
		break;
	case NFSPROC3_READDIRPLUS:
		 if (!xdr_readdirplus3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.readdirplus_body))
			 return FALSE;
		break;
	case NFSPROC3_FSSTAT:
		 if (!xdr_fsstat3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.fsstat_body))
			 return FALSE;
		break;
	case NFSPROC3_FSINFO:
		 if (!xdr_fsinfo3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.fsinfo_body))
			 return FALSE;
		break;
	case NFSPROC3_PATHCONF:
		 if (!xdr_pathconf3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.pathconf_body))
			 return FALSE;
		break;
	case NFSPROC3_COMMIT:
		 if (!xdr_commit3_proc_call_body (xdrs, &objp->nfsv3_call_body_u.commit_body))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_nfsv4_call_body (XDR *xdrs, nfsv4_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	switch (objp->proc) {
	case 0:
		 if (!xdr_empty_proc_body (xdrs, &objp->nfsv4_call_body_u.null_body))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_nfs_call_body (XDR *xdrs, nfs_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	switch (objp->vers) {
	case 3:
		 if (!xdr_nfsv3_call_body (xdrs, &objp->nfs_call_body_u.body3))
			 return FALSE;
		break;
	case 4:
		 if (!xdr_nfsv4_call_body (xdrs, &objp->nfs_call_body_u.body4))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_mnt3_proc_call_body (XDR *xdrs, mnt3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->args, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_umnt3_proc_call_body (XDR *xdrs, umnt3_proc_call_body *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->args, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mountv3_call_body (XDR *xdrs, mountv3_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	switch (objp->proc) {
	case MOUNTPROC3_NULL:
		 if (!xdr_empty_proc_body (xdrs, &objp->mountv3_call_body_u.null_body))
			 return FALSE;
		break;
	case MOUNTPROC3_MNT:
		 if (!xdr_mnt3_proc_call_body (xdrs, &objp->mountv3_call_body_u.mnt_body))
			 return FALSE;
		break;
	case MOUNTPROC3_DUMP:
		 if (!xdr_empty_proc_body (xdrs, &objp->mountv3_call_body_u.dump_body))
			 return FALSE;
		break;
	case MOUNTPROC3_UMNT:
		 if (!xdr_umnt3_proc_call_body (xdrs, &objp->mountv3_call_body_u.umnt_body))
			 return FALSE;
		break;
	case MOUNTPROC3_UMNTALL:
		 if (!xdr_empty_proc_body (xdrs, &objp->mountv3_call_body_u.umntall_body))
			 return FALSE;
		break;
	case MOUNTPROC3_EXPORT:
		 if (!xdr_empty_proc_body (xdrs, &objp->mountv3_call_body_u.export_body))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_mount_call_body (XDR *xdrs, mount_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	switch (objp->vers) {
	case 3:
		 if (!xdr_mountv3_call_body (xdrs, &objp->mount_call_body_u.body))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_program_call_body (XDR *xdrs, program_call_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->prog))
		 return FALSE;
	switch (objp->prog) {
	case NFS_PROGRAM:
		 if (!xdr_nfs_call_body (xdrs, &objp->program_call_body_u.nbody))
			 return FALSE;
		break;
	case MOUNT_PROGRAM:
		 if (!xdr_mount_call_body (xdrs, &objp->program_call_body_u.mbody))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_lwcall_body (XDR *xdrs, lwcall_body *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->rpcvers))
		 return FALSE;
	switch (objp->rpcvers) {
	case 2:
		 if (!xdr_program_call_body (xdrs, &objp->lwcall_body_u.body))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
