/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc2.h"

bool_t
xdr_rpc2_auth_flavor (XDR *xdrs, rpc2_auth_flavor *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_opaque_auth (XDR *xdrs, rpc2_opaque_auth *objp)
{
	 if (!xdr_rpc2_auth_flavor (xdrs, &objp->flavor))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->body.body_val, (u_int *) &objp->body.body_len, 400))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_authsys_parms (XDR *xdrs, rpc2_authsys_parms *objp)
{
	 if (!xdr_u_int (xdrs, &objp->stamp))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->machinename, 255))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gid))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->gids.gids_val, (u_int *) &objp->gids.gids_len, 16,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_msg_type (XDR *xdrs, rpc2_msg_type *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_reply_stat (XDR *xdrs, rpc2_reply_stat *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_accept_stat (XDR *xdrs, rpc2_accept_stat *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_reject_stat (XDR *xdrs, rpc2_reject_stat *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_auth_stat (XDR *xdrs, rpc2_auth_stat *objp)
{
	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_call_body (XDR *xdrs, rpc2_call_body *objp)
{
	register int32_t *buf;
    int32_t dummy;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->rpcvers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		dummy = IXDR_PUT_U_LONG(buf, objp->rpcvers);
		dummy = IXDR_PUT_U_LONG(buf, objp->prog);
		dummy = IXDR_PUT_U_LONG(buf, objp->vers);
		dummy = IXDR_PUT_U_LONG(buf, objp->proc);
		}
		 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
			 return FALSE;
		 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->rpcvers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		objp->rpcvers = IXDR_GET_U_LONG(buf);
		objp->prog = IXDR_GET_U_LONG(buf);
		objp->vers = IXDR_GET_U_LONG(buf);
		objp->proc = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
			 return FALSE;
		 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->rpcvers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_mismatch_info (XDR *xdrs, rpc2_mismatch_info *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->low))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->high))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_accepted_reply_data (XDR *xdrs, rpc2_accepted_reply_data *objp)
{
	

	 if (!xdr_rpc2_accept_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case RPC2_SUCCESS:
		 if (!xdr_opaque (xdrs, objp->rpc2_accepted_reply_data_u.results, 0))
			 return FALSE;
		break;
	case RPC2_PROG_MISMATCH:
		 if (!xdr_rpc2_mismatch_info (xdrs, &objp->rpc2_accepted_reply_data_u.mismatch_info))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_rpc2_accepted_reply (XDR *xdrs, rpc2_accepted_reply *objp)
{
	

	 if (!xdr_rpc2_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_rpc2_accepted_reply_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc2_rejected_reply (XDR *xdrs, rpc2_rejected_reply *objp)
{
	

	 if (!xdr_rpc2_reject_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case RPC2_RPC_MISMATCH:
		 if (!xdr_rpc2_mismatch_info (xdrs, &objp->rpc2_rejected_reply_u.mismatch_info))
			 return FALSE;
		break;
	case RPC2_AUTH_ERROR:
		 if (!xdr_rpc2_auth_stat (xdrs, &objp->rpc2_rejected_reply_u.stat))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_rpc2_reply_body (XDR *xdrs, rpc2_reply_body *objp)
{
	

	 if (!xdr_rpc2_reply_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case RPC2_MSG_ACCEPTED:
		 if (!xdr_rpc2_accepted_reply (xdrs, &objp->rpc2_reply_body_u.areply))
			 return FALSE;
		break;
	case RPC2_MSG_DENIED:
		 if (!xdr_rpc2_rejected_reply (xdrs, &objp->rpc2_reply_body_u.rreply))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_rpc2_rpc_msg_body (XDR *xdrs, rpc2_rpc_msg_body *objp)
{
	

	 if (!xdr_rpc2_msg_type (xdrs, &objp->mtype))
		 return FALSE;
	switch (objp->mtype) {
	case RPC2_CALL:
		 if (!xdr_rpc2_call_body (xdrs, &objp->rpc2_rpc_msg_body_u.cbody))
			 return FALSE;
		break;
	case RPC2_REPLY:
		 if (!xdr_rpc2_reply_body (xdrs, &objp->rpc2_rpc_msg_body_u.rbody))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_rpc2_rpc_msg (XDR *xdrs, rpc2_rpc_msg *objp)
{
	

	 if (!xdr_u_int (xdrs, &objp->xid))
		 return FALSE;
	 if (!xdr_rpc2_rpc_msg_body (xdrs, &objp->body))
		 return FALSE;
	return TRUE;
}
