.\"     Title: Likewise Open
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 03/14/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "LIKEWISE OPEN" "7" "03/14/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
likewise\-open \- A suite of tools and services for joining Linux, Unix, and OS X clients to Active Directory domains
.SH "DESCRIPTION"
.PP
Likewise Open is a set of tools and services to enable joining hosts to an Active DIrectory (AD) domain in a single step. The software performs all the necessary system management configuration to enable PAM aware host services to authenticate AD domain users and honor the user's existing set of domain group memberships.
.SH "SUPPORT"
.PP
Likewise Open is a open source initiate of Likewise Software and is open for full community involvement. More information about Likewise Open and Likewise Software can be found at
\fIhttp://www.likewisesoftware.com/community/\fR. You may subscribe to the Likewise Open project mailing lists at
\fIhttp://lists.likewisesoftware.com/\fR.
.SH "SEE ALSO"
.PP

\fBdomainjoin\-cli(8)\fR,
\fBdomainjoin\-gui(8)\fR
.SH "VERSION"
.PP
This man page is correct for Likewise Open version 4.1.
