#!/bin/sh

if  test -f ../support/simple_eval_tools.sh  ; then
  . ../support/simple_eval_tools.sh
  versionfile=$SNMP_BASEDIR/../../../dist/autoconf-version
  configurefile=$SNMP_BASEDIR/../../../configure
else
  . ../eval_tools.sh
  versionfile=$SNMP_BASEDIR/../dist/autoconf-version
  configurefile=$SNMP_BASEDIR/../configure
fi

HEADER Checking the Net-SNMP configure script validity

VERSIONNEEDED=`cat $versionfile`

CAPTURE "egrep Generated.by.GNU.Autoconf.$VERSIONNEEDED $configurefile"
CHECKORDIE Net-SNMP
SAVE_RESULTS

echo "bogus" > $SNMP_TMPDIR/foo.pid
FINISHED
