/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>

#include "rpc2.h"
#include "nfs3_procs.h"


#ifdef __cplusplus
extern "C" {
#endif


struct empty_proc_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
};
typedef struct empty_proc_body empty_proc_body;

struct getattr3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	GETATTR3args agrs;
};
typedef struct getattr3_proc_call_body getattr3_proc_call_body;

struct setattr3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	SETATTR3args agrs;
};
typedef struct setattr3_proc_call_body setattr3_proc_call_body;

struct lookup3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	LOOKUP3args args;
};
typedef struct lookup3_proc_call_body lookup3_proc_call_body;

struct access3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	ACCESS3args args;
};
typedef struct access3_proc_call_body access3_proc_call_body;

struct readlink3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	READLINK3args args;
};
typedef struct readlink3_proc_call_body readlink3_proc_call_body;

struct read3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	READ3args args;
};
typedef struct read3_proc_call_body read3_proc_call_body;

struct write3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	WRITE3args args;
};
typedef struct write3_proc_call_body write3_proc_call_body;

struct create3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	CREATE3args args;
};
typedef struct create3_proc_call_body create3_proc_call_body;

struct mkdir3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	MKDIR3args args;
};
typedef struct mkdir3_proc_call_body mkdir3_proc_call_body;

struct symlink3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	SYMLINK3args args;
};
typedef struct symlink3_proc_call_body symlink3_proc_call_body;

struct mknod3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	MKNOD3args args;
};
typedef struct mknod3_proc_call_body mknod3_proc_call_body;

struct remove3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	REMOVE3args args;
};
typedef struct remove3_proc_call_body remove3_proc_call_body;

struct rmdir3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	RMDIR3args args;
};
typedef struct rmdir3_proc_call_body rmdir3_proc_call_body;

struct rename3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	RENAME3args args;
};
typedef struct rename3_proc_call_body rename3_proc_call_body;

struct link3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	LINK3args args;
};
typedef struct link3_proc_call_body link3_proc_call_body;

struct readdir3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	READDIR3args args;
};
typedef struct readdir3_proc_call_body readdir3_proc_call_body;

struct readdirplus3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	READDIRPLUS3args args;
};
typedef struct readdirplus3_proc_call_body readdirplus3_proc_call_body;

struct fsstat3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	FSSTAT3args args;
};
typedef struct fsstat3_proc_call_body fsstat3_proc_call_body;

struct fsinfo3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	FSINFO3args args;
};
typedef struct fsinfo3_proc_call_body fsinfo3_proc_call_body;

struct pathconf3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	PATHCONF3args args;
};
typedef struct pathconf3_proc_call_body pathconf3_proc_call_body;

struct commit3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	COMMIT3args args;
};
typedef struct commit3_proc_call_body commit3_proc_call_body;

struct nfsv3_call_body {
	u_int proc;
	union {
		empty_proc_body null_body;
		getattr3_proc_call_body getattr_body;
		setattr3_proc_call_body setattr_body;
		lookup3_proc_call_body lookup_body;
		access3_proc_call_body access_body;
		readlink3_proc_call_body readlink_body;
		read3_proc_call_body read_body;
		write3_proc_call_body write_body;
		create3_proc_call_body create_body;
		mkdir3_proc_call_body mkdir_body;
		symlink3_proc_call_body symlink_body;
		mknod3_proc_call_body mknod_body;
		remove3_proc_call_body remove_body;
		rmdir3_proc_call_body rmdir_body;
		rename3_proc_call_body rename_body;
		link3_proc_call_body link_body;
		readdir3_proc_call_body readdir_body;
		readdirplus3_proc_call_body readdirplus_body;
		fsstat3_proc_call_body fsstat_body;
		fsinfo3_proc_call_body fsinfo_body;
		pathconf3_proc_call_body pathconf_body;
		commit3_proc_call_body commit_body;
	} nfsv3_call_body_u;
};
typedef struct nfsv3_call_body nfsv3_call_body;

struct nfsv4_call_body {
	u_int proc;
	union {
		empty_proc_body null_body;
	} nfsv4_call_body_u;
};
typedef struct nfsv4_call_body nfsv4_call_body;

struct nfs_call_body {
	u_int vers;
	union {
		nfsv3_call_body body3;
		nfsv4_call_body body4;
	} nfs_call_body_u;
};
typedef struct nfs_call_body nfs_call_body;

struct mnt3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	char *args;
};
typedef struct mnt3_proc_call_body mnt3_proc_call_body;

struct umnt3_proc_call_body {
	rpc2_opaque_auth cred;
	rpc2_opaque_auth verf;
	char *args;
};
typedef struct umnt3_proc_call_body umnt3_proc_call_body;

struct mountv3_call_body {
	u_int proc;
	union {
		empty_proc_body null_body;
		mnt3_proc_call_body mnt_body;
		empty_proc_body dump_body;
		umnt3_proc_call_body umnt_body;
		empty_proc_body umntall_body;
		empty_proc_body export_body;
	} mountv3_call_body_u;
};
typedef struct mountv3_call_body mountv3_call_body;

struct mount_call_body {
	u_int vers;
	union {
		mountv3_call_body body;
	} mount_call_body_u;
};
typedef struct mount_call_body mount_call_body;

struct program_call_body {
	u_int prog;
	union {
		nfs_call_body nbody;
		mount_call_body mbody;
	} program_call_body_u;
};
typedef struct program_call_body program_call_body;

struct lwcall_body {
	u_int rpcvers;
	union {
		program_call_body body;
	} lwcall_body_u;
};
typedef struct lwcall_body lwcall_body;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_empty_proc_body (XDR *, empty_proc_body*);
extern  bool_t xdr_getattr3_proc_call_body (XDR *, getattr3_proc_call_body*);
extern  bool_t xdr_setattr3_proc_call_body (XDR *, setattr3_proc_call_body*);
extern  bool_t xdr_lookup3_proc_call_body (XDR *, lookup3_proc_call_body*);
extern  bool_t xdr_access3_proc_call_body (XDR *, access3_proc_call_body*);
extern  bool_t xdr_readlink3_proc_call_body (XDR *, readlink3_proc_call_body*);
extern  bool_t xdr_read3_proc_call_body (XDR *, read3_proc_call_body*);
extern  bool_t xdr_write3_proc_call_body (XDR *, write3_proc_call_body*);
extern  bool_t xdr_create3_proc_call_body (XDR *, create3_proc_call_body*);
extern  bool_t xdr_mkdir3_proc_call_body (XDR *, mkdir3_proc_call_body*);
extern  bool_t xdr_symlink3_proc_call_body (XDR *, symlink3_proc_call_body*);
extern  bool_t xdr_mknod3_proc_call_body (XDR *, mknod3_proc_call_body*);
extern  bool_t xdr_remove3_proc_call_body (XDR *, remove3_proc_call_body*);
extern  bool_t xdr_rmdir3_proc_call_body (XDR *, rmdir3_proc_call_body*);
extern  bool_t xdr_rename3_proc_call_body (XDR *, rename3_proc_call_body*);
extern  bool_t xdr_link3_proc_call_body (XDR *, link3_proc_call_body*);
extern  bool_t xdr_readdir3_proc_call_body (XDR *, readdir3_proc_call_body*);
extern  bool_t xdr_readdirplus3_proc_call_body (XDR *, readdirplus3_proc_call_body*);
extern  bool_t xdr_fsstat3_proc_call_body (XDR *, fsstat3_proc_call_body*);
extern  bool_t xdr_fsinfo3_proc_call_body (XDR *, fsinfo3_proc_call_body*);
extern  bool_t xdr_pathconf3_proc_call_body (XDR *, pathconf3_proc_call_body*);
extern  bool_t xdr_commit3_proc_call_body (XDR *, commit3_proc_call_body*);
extern  bool_t xdr_nfsv3_call_body (XDR *, nfsv3_call_body*);
extern  bool_t xdr_nfsv4_call_body (XDR *, nfsv4_call_body*);
extern  bool_t xdr_nfs_call_body (XDR *, nfs_call_body*);
extern  bool_t xdr_mnt3_proc_call_body (XDR *, mnt3_proc_call_body*);
extern  bool_t xdr_umnt3_proc_call_body (XDR *, umnt3_proc_call_body*);
extern  bool_t xdr_mountv3_call_body (XDR *, mountv3_call_body*);
extern  bool_t xdr_mount_call_body (XDR *, mount_call_body*);
extern  bool_t xdr_program_call_body (XDR *, program_call_body*);
extern  bool_t xdr_lwcall_body (XDR *, lwcall_body*);

#else /* K&R C */
extern bool_t xdr_empty_proc_body ();
extern bool_t xdr_getattr3_proc_call_body ();
extern bool_t xdr_setattr3_proc_call_body ();
extern bool_t xdr_lookup3_proc_call_body ();
extern bool_t xdr_access3_proc_call_body ();
extern bool_t xdr_readlink3_proc_call_body ();
extern bool_t xdr_read3_proc_call_body ();
extern bool_t xdr_write3_proc_call_body ();
extern bool_t xdr_create3_proc_call_body ();
extern bool_t xdr_mkdir3_proc_call_body ();
extern bool_t xdr_symlink3_proc_call_body ();
extern bool_t xdr_mknod3_proc_call_body ();
extern bool_t xdr_remove3_proc_call_body ();
extern bool_t xdr_rmdir3_proc_call_body ();
extern bool_t xdr_rename3_proc_call_body ();
extern bool_t xdr_link3_proc_call_body ();
extern bool_t xdr_readdir3_proc_call_body ();
extern bool_t xdr_readdirplus3_proc_call_body ();
extern bool_t xdr_fsstat3_proc_call_body ();
extern bool_t xdr_fsinfo3_proc_call_body ();
extern bool_t xdr_pathconf3_proc_call_body ();
extern bool_t xdr_commit3_proc_call_body ();
extern bool_t xdr_nfsv3_call_body ();
extern bool_t xdr_nfsv4_call_body ();
extern bool_t xdr_nfs_call_body ();
extern bool_t xdr_mnt3_proc_call_body ();
extern bool_t xdr_umnt3_proc_call_body ();
extern bool_t xdr_mountv3_call_body ();
extern bool_t xdr_mount_call_body ();
extern bool_t xdr_program_call_body ();
extern bool_t xdr_lwcall_body ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
