
#define EVT_SECONDS_IN_MINUTE (60)
#define EVT_SECONDS_IN_HOUR   (60 * EVT_SECONDS_IN_MINUTE)
#define EVT_SECONDS_IN_DAY    (24 * EVT_SECONDS_IN_HOUR)

#define EVT_BYTES_IN_KB 	(1024)
#define EVT_BYTES_IN_MB   	(1024 * EVT_BYTES_IN_KB)
#define EVT_BYTES_IN_GB    	(1024 * EVT_BYTES_IN_MB)

#define EVT_RECS_IN_K 		(1000)
#define EVT_RECS_IN_M   	(1000 * EVT_RECS_IN_K)

