/*
 * Copyright (c) Likewise Software.  All rights Reserved.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the license, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.  You should have received a copy
 * of the GNU Lesser General Public License along with this program.  If
 * not, see <http://www.gnu.org/licenses/>.
 *
 * LIKEWISE SOFTWARE MAKES THIS SOFTWARE AVAILABLE UNDER OTHER LICENSING
 * TERMS AS WELL.  IF YOU HAVE ENTERED INTO A SEPARATE LICENSE AGREEMENT
 * WITH LIKEWISE SOFTWARE, THEN YOU MAY ELECT TO USE THE SOFTWARE UNDER THE
 * TERMS OF THAT SOFTWARE LICENSE AGREEMENT INSTEAD OF THE TERMS OF THE GNU
 * LESSER GENERAL PUBLIC LICENSE, NOTWITHSTANDING THE ABOVE NOTICE.  IF YOU
 * HAVE QUESTIONS, OR WISH TO REQUEST A COPY OF THE ALTERNATE LICENSING
 * TERMS OFFERED BY LIKEWISE SOFTWARE, PLEASE CONTACT LIKEWISE SOFTWARE AT
 * license@likewisesoftware.com
 */

/*
 * Module Name:
 *
 *        sddlsid-table.h
 *
 * Abstract:
 *
 *        Sid String and constants information table
 *
 * Authors: Wei Fu (wfu@likewise.com)
 *
 */

#define S SIDRID_MAPPING
S ( SECURITY_ANONYMOUS_LOGON_RID, SDDL_ANONYMOUS, SID_SECURITY_ANONYMOUS_LOGON_RID )
S ( SECURITY_CREATOR_GROUP_RID, SDDL_CREATOR_GROUP, SID_SECURITY_CREATOR_OWNER_RID )
S ( SECURITY_CREATOR_OWNER_RID, SDDL_CREATOR_OWNER, SID_SECURITY_CREATOR_GROUP_RID )
S ( SECURITY_AUTHENTICATED_USER_RID, SDDL_AUTHENTICATED_USERS, SID_SECURITY_AUTHENTICATED_USER_RID )
S ( SECURITY_NETWORK_RID, SDDL_NETWORK, SID_SECURITY_NETWORK_RID )
S ( SECURITY_PRINCIPAL_SELF_RID, SDDL_PERSONAL_SELF, SID_SECURITY_PRINCIPAL_SELF_RID )
S ( SECURITY_RESTRICTED_CODE_RID, SDDL_RESTRICTED_CODE, SID_SECURITY_RESTRICTED_CODE_RID )
S ( SECURITY_SERVICE_RID, SDDL_SERVICE, SID_SECURITY_SERVICE_RID )
S ( SECURITY_LOCAL_SYSTEM_RID, SDDL_LOCAL_SYSTEM, SID_SECURITY_LOCAL_SYSTEM_RID )
S ( SECURITY_INTERACTIVE_RID, SDDL_INTERACTIVE, SID_SECURITY_INTERACTIVE_RID )
#undef S

#if 0
S ( DOMAIN_ALIAS_RID_ACCOUNT_OPS, SDDL_ACCOUNT_OPERATORS )
S ( DOMAIN_ALIAS_RID_ADMINS, SDDL_BUILTIN_ADMINISTRATORS )
S ( DOMAIN_ALIAS_RID_GUESTS, SDDL_BUILTIN_GUESTS )
S ( DOMAIN_ALIAS_RID_BACKUP_OPS, SDDL_BACKUP_OPERATORS )
S ( DOMAIN_ALIAS_RID_USERS, SDDL_BUILTIN_USERS )
S ( DOMAIN_GROUP_RID_CERT_ADMINS, SDDL_CERT_SERV_ADMINISTRATORS )
S ( DOMAIN_GROUP_RID_ADMINS, SDDL_DOMAIN_ADMINISTRATORS )
S ( DOMAIN_GROUP_RID_COMPUTERS, SDDL_DOMAIN_COMPUTERS )
S ( DOMAIN_GROUP_RID_CONTROLLERS, SDDL_DOMAIN_DOMAIN_CONTROLLERS )
S ( DOMAIN_GROUP_RID_GUESTS, SDDL_DOMAIN_GUESTS )
S ( DOMAIN_GROUP_RID_USERS, SDDL_DOMAIN_USERS )
S ( DOMAIN_GROUP_RID_ENTERPRISE_ADMINS, SDDL_ENTERPRISE_ADMINS )
S ( DOMAIN_USER_RID_ADMIN, SDDL_LOCAL_ADMIN )
S ( DOMAIN_USER_RID_GUEST, SDDL_LOCAL_GUEST )
S ( DOMAIN_ALIAS_RID_NETWORK_CONFIGURATION_OPS, SDDL_NETWORK_CONFIGURATION_OPS )
S ( DOMAIN_GROUP_RID_POLICY_ADMINS, SDDL_GROUP_POLICY_ADMINS )
S ( DOMAIN_ALIAS_RID_PRINT_OPS, SDDL_PRINTER_OPERATORS )
S ( DOMAIN_ALIAS_RID_POWER_USERS, SDDL_POWER_USERS )
S ( DOMAIN_ALIAS_RID_REMOTE_DESKTOP_USERS, SDDL_REMOTE_DESKTOP )
S ( DOMAIN_ALIAS_RID_REPLICATOR, SDDL_REPLICATOR )
S ( DOMAIN_ALIAS_RID_RAS_SERVERS, SDDL_RAS_SERVERS )
S ( DOMAIN_ALIAS_RID_PREW2KCOMPACCESS, SDDL_ALIAS_PREW2KCOMPACC )
S ( DOMAIN_GROUP_RID_SCHEMA_ADMINS, SDDL_SCHEMA_ADMINISTRATORS )
S ( DOMAIN_ALIAS_RID_SYSTEM_OPS, SDDL_SERVER_OPERATORS )

S ( SECURITY_SERVER_LOGON_RID, SDDL_ENTERPRISE_DOMAIN_CONTROLLERS )
S ( SECURITY_MANDATORY_HIGH_RID, SDDL_ML_HIGH )
S ( SECURITY_MANDATORY_MEDIUM_RID, SDDL_ML_MEDIUM )
S ( SECURITY_MANDATORY_LOW_RID, SDDL_ML_LOW )
S ( SECURITY_MANDATORY_SYSTEM_RID, SDDL_ML_SYSTEM )
S ( SECURITY_LOCAL_SERVICE_RID, SDDL_LOCAL_SERVICE )
S ( SECURITY_NETWORK_SERVICE_RID, SDDL_NETWORK_SERVICE )
#endif
