#! /bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
# We are using bash instead of sh because sh does not support echo -n
#
# Copyright (c) Likewise Corporation 2006
# Author: Gerald Carter <jerry@likewise.com>
#
# /etc/init.d/eventlogd
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 20 9
#LWI_STARTUP_TYPE_REDHAT# description: Start and Stop the Likewise Likewise Eventlog
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: eventlogd
#LWI_STARTUP_TYPE_SUSE# Required-Start: $network $remote_fs rpcd
#LWI_STARTUP_TYPE_SUSE# Required-Stop: $network $remote_fs
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop: 0 1 2 6
#LWI_STARTUP_TYPE_SUSE# Description: Start and Stop the Likewise Likewise Eventlog
#LWI_STARTUP_TYPE_SUSE### END INIT INFO

PREFIX="PREFIX_DIR"
SERVICE_NAME="eventlog"

. PREFIX_DIR/bin/init-lwsm.sh
