#! /bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
#
# Copyright (c) Likewise Corporation 2010
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 21 9
#LWI_STARTUP_TYPE_REDHAT# description: Start Likewise Open services
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: lsassd
#LWI_STARTUP_TYPE_SUSE# Required-Start: $network $remote_fs
#LWI_STARTUP_TYPE_SUSE# Required-Stop:
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop:
#LWI_STARTUP_TYPE_SUSE# Description: Start Likewise Open services
#LWI_STARTUP_TYPE_SUSE### END INIT INFO

PREFIX="PREFIX_DIR"
SERVICE_NAME="likewise"

. PREFIX_DIR/bin/init-likewise.sh
