#! /bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
#
# Copyright (c) Likewise Corporation 2006
# Author: Gerald Carter <jerry@likewise.com>
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 17 9
#LWI_STARTUP_TYPE_REDHAT# description: Start and Stop Likewise Service Manager
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: lwsmd
#LWI_STARTUP_TYPE_SUSE# Required-Start:
#LWI_STARTUP_TYPE_SUSE# Required-Stop:
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop: 0 1 2 6
#LWI_STARTUP_TYPE_SUSE# Description: Start and Stop Likewise Service Manager
#LWI_STARTUP_TYPE_SUSE### END INIT INFO

PROG_DESC="Likewise Service Manager"
PROG_BIN=PREFIX_DIR/sbin/lwsmd
PROG_ARGS="--start-as-daemon"
PIDFILE=/var/run/lwsmd.pid
SCRIPTNAME="lwsmd"

. PREFIX_DIR/bin/init-base.sh
