#!/bin/sh
make()
{
    TICKETCOPY_SOURCES="\
        ticketcopy.c"

    mk_program \
	PROGRAM=ticketcopy \
	SOURCES="$TICKETCOPY_SOURCES" \
        INSTALLDIR="${MK_LIBEXECDIR}" \
	INCLUDEDIRS="../../include" \
	HEADERDEPS="lw/attrs.h lw/types.h lsa/lsa.h lwerror.h lwkrb5.h"
	LIBDEPS="lsaclient lsacommon lwadvapi lwadvapi_nothr lwbase lwbase_nothr"

    mk_stage \
        DESTDIR="${LW_SYSCONFDIR}/LaunchAgents" \
        com.likewisesoftware.ticketcopy.plist
}
