/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CyrusSasl_Sasl */

#ifndef _Included_CyrusSasl_Sasl
#define _Included_CyrusSasl_Sasl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_GenericClient */

#ifndef _Included_CyrusSasl_GenericClient
#define _Included_CyrusSasl_GenericClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CyrusSasl_GenericClient
 * Method:    jni_sasl_client_start
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericClient_jni_1sasl_1client_1start
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     CyrusSasl_GenericClient
 * Method:    jni_sasl_client_step
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericClient_jni_1sasl_1client_1step
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_ClientFactory */

#ifndef _Included_CyrusSasl_ClientFactory
#define _Included_CyrusSasl_ClientFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CyrusSasl_ClientFactory
 * Method:    jni_sasl_client_init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_CyrusSasl_ClientFactory_jni_1sasl_1client_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CyrusSasl_ClientFactory
 * Method:    jni_sasl_client_new
 * Signature: (Ljava/lang/String;Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_CyrusSasl_ClientFactory_jni_1sasl_1client_1new
  (JNIEnv *, jobject, jstring, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_GenericCommon */

#ifndef _Included_CyrusSasl_GenericCommon
#define _Included_CyrusSasl_GenericCommon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_set_prop_string
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1set_1prop_1string
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_set_prop_int
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1set_1prop_1int
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_set_prop_bytes
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1set_1prop_1bytes
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_set_server
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1set_1server
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_set_client
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1set_1client
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_setSecurity
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1setSecurity
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_getSecurity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1getSecurity
  (JNIEnv *, jobject, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_encode
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1encode
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_decode
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1decode
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     CyrusSasl_GenericCommon
 * Method:    jni_sasl_dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CyrusSasl_GenericCommon_jni_1sasl_1dispose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslClient */

#ifndef _Included_CyrusSasl_SaslClient
#define _Included_CyrusSasl_SaslClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslClientFactory */

#ifndef _Included_CyrusSasl_SaslClientFactory
#define _Included_CyrusSasl_SaslClientFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslException */

#ifndef _Included_CyrusSasl_SaslException
#define _Included_CyrusSasl_SaslException
#ifdef __cplusplus
extern "C" {
#endif
#undef CyrusSasl_SaslException_serialVersionUID
#define CyrusSasl_SaslException_serialVersionUID -3042686055658047285LL
#undef CyrusSasl_SaslException_serialVersionUID
#define CyrusSasl_SaslException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslInputStream */

#ifndef _Included_CyrusSasl_SaslInputStream
#define _Included_CyrusSasl_SaslInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef CyrusSasl_SaslInputStream_SKIP_BUFFER_SIZE
#define CyrusSasl_SaslInputStream_SKIP_BUFFER_SIZE 2048L
#undef CyrusSasl_SaslInputStream_DoEncrypt
#define CyrusSasl_SaslInputStream_DoEncrypt 1L
#undef CyrusSasl_SaslInputStream_DoDebug
#define CyrusSasl_SaslInputStream_DoDebug 0L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslOutputStream */

#ifndef _Included_CyrusSasl_SaslOutputStream
#define _Included_CyrusSasl_SaslOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef CyrusSasl_SaslOutputStream_DoEncrypt
#define CyrusSasl_SaslOutputStream_DoEncrypt 1L
#undef CyrusSasl_SaslOutputStream_DoDebug
#define CyrusSasl_SaslOutputStream_DoDebug 0L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslUtils */

#ifndef _Included_CyrusSasl_SaslUtils
#define _Included_CyrusSasl_SaslUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_ServerFactory */

#ifndef _Included_CyrusSasl_ServerFactory
#define _Included_CyrusSasl_ServerFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CyrusSasl_ServerFactory
 * Method:    jni_sasl_server_init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_CyrusSasl_ServerFactory_jni_1sasl_1server_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CyrusSasl_ServerFactory
 * Method:    jni_sasl_server_new
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_CyrusSasl_ServerFactory_jni_1sasl_1server_1new
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     CyrusSasl_ServerFactory
 * Method:    jni_sasl_server_getlist
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CyrusSasl_ServerFactory_jni_1sasl_1server_1getlist
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslServerFactory */

#ifndef _Included_CyrusSasl_SaslServerFactory
#define _Included_CyrusSasl_SaslServerFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_SaslServer */

#ifndef _Included_CyrusSasl_SaslServer
#define _Included_CyrusSasl_SaslServer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class CyrusSasl_GenericServer */

#ifndef _Included_CyrusSasl_GenericServer
#define _Included_CyrusSasl_GenericServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CyrusSasl_GenericServer
 * Method:    jni_sasl_server_start
 * Signature: (ILjava/lang/String;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericServer_jni_1sasl_1server_1start
  (JNIEnv *, jobject, jint, jstring, jbyteArray, jint);

/*
 * Class:     CyrusSasl_GenericServer
 * Method:    jni_sasl_server_step
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CyrusSasl_GenericServer_jni_1sasl_1server_1step
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
