[
uuid(12345778-1234-abcd-ef00-0123456789ab),
version(0.0),
endpoint("ncacn_np:[\\pipe\\lsarpc], ncacn_np:[\\pipe\\netlogon], ncacn_np:[\\pipe\\lsass]"),
pointer_default(unique)
]
interface lsa
{

cpp_quote("#ifdef DCERPC_STUB_BUILD")

#include <lw/security-types.h>
#include <lw/rpc/lsa.h>

    /* LsaPolicyInformation union returned from LsaQueryInfoPolicy */
    typedef [switch_type(UINT16)] union lsa_policy_information {
        [case(LSA_POLICY_INFO_AUDIT_LOG)]        AuditLogInfo        audit_log;
        [case(LSA_POLICY_INFO_AUDIT_EVENTS)]     AuditEventsInfo     audit_events;
        [case(LSA_POLICY_INFO_DOMAIN)]           LsaDomainInfo       domain;
        [case(LSA_POLICY_INFO_PD)]               PDAccountInfo       pd;
        [case(LSA_POLICY_INFO_ACCOUNT_DOMAIN)]   LsaDomainInfo       account_domain;
        [case(LSA_POLICY_INFO_ROLE)]             ServerRole          role;
        [case(LSA_POLICY_INFO_REPLICA)]          ReplicaSourceInfo   replica;
        [case(LSA_POLICY_INFO_QUOTA)]            DefaultQuotaInfo    quota;
        [case(LSA_POLICY_INFO_DB)]               ModificationInfo    db;
        [case(LSA_POLICY_INFO_AUDIT_FULL_SET)]   AuditFullSetInfo    audit_set;
        [case(LSA_POLICY_INFO_AUDIT_FULL_QUERY)] AuditFullQueryInfo  audit_query;
        [case(LSA_POLICY_INFO_DNS)]              DnsDomainInfo       dns;
    } LsaPolicyInformation;

cpp_quote("#endif")


	/* function 0x00 */
    NTSTATUS LsaClose(
        [in,out,context_handle] void **phInOut
        );

    NTSTATUS lsa_Function01();
    NTSTATUS lsa_Function02();
    NTSTATUS lsa_Function03();
    NTSTATUS lsa_Function04();
    NTSTATUS lsa_Function05();
    NTSTATUS lsa_Function06();

	/* function 0x07 */
    NTSTATUS LsaQueryInfoPolicy(
        [in] POLICY_HANDLE hPolicy,
        [in] UINT16 level,
        [out,switch_is(level)] LsaPolicyInformation **info
        );

    NTSTATUS lsa_Function08();
    NTSTATUS lsa_Function09();
    NTSTATUS lsa_Function0a();
    NTSTATUS lsa_Function0b();
    NTSTATUS lsa_Function0c();
    NTSTATUS lsa_Function0d();

	/* function 0x0e */
    NTSTATUS LsaLookupNames(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UNICODE_STRING *pNames,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count
        );

	/* function 0x0f */
    NTSTATUS LsaLookupSids(
        [in] POLICY_HANDLE hPolicy,
        [in] SID_ARRAY *pSids,
        [out] RefDomainList **domains,
        [in,out] TranslatedNameArray *names,
        [in] UINT16 level,
        [in,out] UINT32 *count
        );

    NTSTATUS lsa_Function10();
    NTSTATUS lsa_Function11();
    NTSTATUS lsa_Function12();
    NTSTATUS lsa_Function13();
    NTSTATUS lsa_Function14();
    NTSTATUS lsa_Function15();
    NTSTATUS lsa_Function16();
    NTSTATUS lsa_Function17();
    NTSTATUS lsa_Function18();
    NTSTATUS lsa_Function19();
    NTSTATUS lsa_Function1a();
    NTSTATUS lsa_Function1b();
    NTSTATUS lsa_Function1c();
    NTSTATUS lsa_Function1d();
    NTSTATUS lsa_Function1e();
    NTSTATUS lsa_Function1f();
    NTSTATUS lsa_Function20();
    NTSTATUS lsa_Function21();
    NTSTATUS lsa_Function22();
    NTSTATUS lsa_Function23();
    NTSTATUS lsa_Function24();
    NTSTATUS lsa_Function25();
    NTSTATUS lsa_Function26();
    NTSTATUS lsa_Function27();
    NTSTATUS lsa_Function28();
    NTSTATUS lsa_Function29();
    NTSTATUS lsa_Function2a();
    NTSTATUS lsa_Function2b();

	/* function 0x2c */
    NTSTATUS LsaOpenPolicy2(
        [in,string,unique] wchar16_t *system_name,
        [in] ObjectAttribute *attrib,
        [in] UINT32 access_mask,
        [out] POLICY_HANDLE *phPolicy
        );

    NTSTATUS lsa_Function2d();

	/* function 0x2e */
    NTSTATUS LsaQueryInfoPolicy2(
        [in] POLICY_HANDLE hPolicy,
        [in] UINT16 level,
        [out,switch_is(level)] LsaPolicyInformation **info
        );

    NTSTATUS lsa_Function2f();
    NTSTATUS lsa_Function30();
    NTSTATUS lsa_Function31();
    NTSTATUS lsa_Function32();
    NTSTATUS lsa_Function33();
    NTSTATUS lsa_Function34();
    NTSTATUS lsa_Function35();
    NTSTATUS lsa_Function36();
    NTSTATUS lsa_Function37();
    NTSTATUS lsa_Function38();

    /* function 0x39 */
    NTSTATUS LsaLookupSids2(
        [in] POLICY_HANDLE hPolicy,
        [in] SID_ARRAY *sids,
        [out] RefDomainList **domains,
        [in,out] TranslatedNameArray2 *names,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );

	/* function 0x3a */
    NTSTATUS LsaLookupNames2(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UNICODE_STRING *pNames,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray2 *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );

    NTSTATUS lsa_Function3b();
    NTSTATUS lsa_Function3c();
    NTSTATUS lsa_Function3d();
    NTSTATUS lsa_Function3e();
    NTSTATUS lsa_Function3f();
    NTSTATUS lsa_Function40();
    NTSTATUS lsa_Function41();
    NTSTATUS lsa_Function42();
    NTSTATUS lsa_Function43();

    NTSTATUS LsaLookupNames3(
        [in] POLICY_HANDLE hPolicy,
        [in,range(0,1000)] UINT32 num_names,
        [in,size_is(num_names)] UNICODE_STRING *pNames,
        [out] RefDomainList **domains,
        [in,out] TranslatedSidArray3 *sids,
        [in] UINT16 level,
        [in,out] UINT32 *count,
        [in] UINT32 unknown1,
        [in] UINT32 unknown2
        );
}


/*
local variables:
mode: c
c-basic-offset: 4
indent-tabs-mode: nil
tab-width: 4
end:
*/
