#!/bin/sh
make()
{
    mk_library \
        LIB="authplugin" \
        SOURCES="mechanism.c" \
        INCLUDEDIRS="../../../include" \
        HEADERDEPS="lw/types.h lwerror.h"
        LDFLAGS="-framework CoreFoundation"
}
