/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockDJGetComputerName.h"

static const char* CMockString_DJGetComputerName = "DJGetComputerName";
static const char* CMockString_ppszComputerName = "ppszComputerName";

typedef struct _CMOCK_DJGetComputerName_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  DWORD ReturnVal;
  PSTR* Expected_ppszComputerName;
  int ReturnThruPtr_ppszComputerName_Used;
  PSTR* ReturnThruPtr_ppszComputerName_Val;
  int ReturnThruPtr_ppszComputerName_Size;
  int IgnoreArg_ppszComputerName;

} CMOCK_DJGetComputerName_CALL_INSTANCE;

static struct MockDJGetComputerNameInstance
{
  int DJGetComputerName_IgnoreBool;
  DWORD DJGetComputerName_FinalReturn;
  CMOCK_MEM_INDEX_TYPE DJGetComputerName_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockDJGetComputerName_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.DJGetComputerName_IgnoreBool)
    Mock.DJGetComputerName_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_DJGetComputerName);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.DJGetComputerName_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockDJGetComputerName_Init(void)
{
  MockDJGetComputerName_Destroy();
}

void MockDJGetComputerName_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

DWORD DJGetComputerName(PSTR* ppszComputerName)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DJGetComputerName);
  cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DJGetComputerName_CallInstance);
  Mock.DJGetComputerName_CallInstance = CMock_Guts_MemNext(Mock.DJGetComputerName_CallInstance);
  if (Mock.DJGetComputerName_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.DJGetComputerName_FinalReturn;
    memcpy(&Mock.DJGetComputerName_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(DWORD));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_ppszComputerName)
  {
    UNITY_SET_DETAILS(CMockString_DJGetComputerName,CMockString_ppszComputerName);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ppszComputerName), (void*)(ppszComputerName), sizeof(PSTR), cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_ppszComputerName_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(ppszComputerName, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)ppszComputerName, (void*)cmock_call_instance->ReturnThruPtr_ppszComputerName_Val,
      cmock_call_instance->ReturnThruPtr_ppszComputerName_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_DJGetComputerName(CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance, PSTR* ppszComputerName)
{
  cmock_call_instance->Expected_ppszComputerName = ppszComputerName;
  cmock_call_instance->IgnoreArg_ppszComputerName = 0;
  cmock_call_instance->ReturnThruPtr_ppszComputerName_Used = 0;
}

void DJGetComputerName_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, DWORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DJGetComputerName_CALL_INSTANCE));
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DJGetComputerName_CallInstance = CMock_Guts_MemChain(Mock.DJGetComputerName_CallInstance, cmock_guts_index);
  Mock.DJGetComputerName_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.DJGetComputerName_IgnoreBool = (int)1;
}

void DJGetComputerName_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DWORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DJGetComputerName_CALL_INSTANCE));
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DJGetComputerName_CallInstance = CMock_Guts_MemChain(Mock.DJGetComputerName_CallInstance, cmock_guts_index);
  Mock.DJGetComputerName_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void DJGetComputerName_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, PSTR* ppszComputerName, DWORD cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DJGetComputerName_CALL_INSTANCE));
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DJGetComputerName_CallInstance = CMock_Guts_MemChain(Mock.DJGetComputerName_CallInstance, cmock_guts_index);
  Mock.DJGetComputerName_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_DJGetComputerName(cmock_call_instance, ppszComputerName);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(DWORD));
  UNITY_CLR_DETAILS();
}

void DJGetComputerName_CMockReturnMemThruPtr_ppszComputerName(UNITY_LINE_TYPE cmock_line, PSTR* ppszComputerName, int cmock_size)
{
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DJGetComputerName_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ppszComputerName_Used = 1;
  cmock_call_instance->ReturnThruPtr_ppszComputerName_Val = ppszComputerName;
  cmock_call_instance->ReturnThruPtr_ppszComputerName_Size = cmock_size;
}

void DJGetComputerName_CMockIgnoreArg_ppszComputerName(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_DJGetComputerName_CALL_INSTANCE* cmock_call_instance = (CMOCK_DJGetComputerName_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.DJGetComputerName_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ppszComputerName = 1;
}

