/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDJGETCOMPUTERNAME_H
#define _MOCKDJGETCOMPUTERNAME_H

#include "DJGetComputerName.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockDJGetComputerName_Init(void);
void MockDJGetComputerName_Destroy(void);
void MockDJGetComputerName_Verify(void);




#define DJGetComputerName_IgnoreAndReturn(cmock_retval) DJGetComputerName_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DJGetComputerName_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, DWORD cmock_to_return);
#define DJGetComputerName_ExpectAnyArgsAndReturn(cmock_retval) DJGetComputerName_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DJGetComputerName_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DWORD cmock_to_return);
#define DJGetComputerName_ExpectAndReturn(ppszComputerName, cmock_retval) DJGetComputerName_CMockExpectAndReturn(__LINE__, ppszComputerName, cmock_retval)
void DJGetComputerName_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, PSTR* ppszComputerName, DWORD cmock_to_return);
#define DJGetComputerName_ReturnThruPtr_ppszComputerName(ppszComputerName) DJGetComputerName_CMockReturnMemThruPtr_ppszComputerName(__LINE__, ppszComputerName, sizeof(*ppszComputerName))
#define DJGetComputerName_ReturnArrayThruPtr_ppszComputerName(ppszComputerName, cmock_len) DJGetComputerName_CMockReturnMemThruPtr_ppszComputerName(__LINE__, ppszComputerName, (int)(cmock_len * (int)sizeof(*ppszComputerName)))
#define DJGetComputerName_ReturnMemThruPtr_ppszComputerName(ppszComputerName, cmock_size) DJGetComputerName_CMockReturnMemThruPtr_ppszComputerName(__LINE__, ppszComputerName, cmock_size)
void DJGetComputerName_CMockReturnMemThruPtr_ppszComputerName(UNITY_LINE_TYPE cmock_line, PSTR* ppszComputerName, int cmock_size);
#define DJGetComputerName_IgnoreArg_ppszComputerName() DJGetComputerName_CMockIgnoreArg_ppszComputerName(__LINE__)
void DJGetComputerName_CMockIgnoreArg_ppszComputerName(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
