#include <compat/dcerpc.idl.include>

[ uuid(5ab2e9b4-3d48-11d2-9ea4-80c5140aaa78), 
  version(1.0),
  pointer_default(ptr)
]

interface echo_encoding {

  typedef [ptr, string] char * encoded_string_t;

  void string_encode(
	[in] handle_t h,
	[in] encoded_string_t str);

  void string_decode(
	[in] handle_t h,
	[out] encoded_string_t* str);
}


