"2074",
"Use %1$s for list of command options",
"Operation %1$s has no binding handle parameter; [auto_handle] assumed",
"File %1$s, line %2$lu: %3$s",
"Must compile stubs with ANSI C compiler to avoid promotion of float to double in operation %1$s",
"Importing IDL file %1$s",
"Creating include file %1$s",
"Legal values are:",
"File %1$s, line %2$lu",
"Name %1$s is declared in file %2$s, line %3$lu",
"Name is referenced in file %1$s, line %2$lu",
"%1$s",
"Options table:",
"Processing attribute configuration file %1$s",
"Running C preprocessor %1$s",
"Compiling stub module %1$s",
"Creating stub module %1$s",
"Deleting stub module %1$s",
"Type %1$s has a represent_as data type %2$s",
"Usage: idl filename [options]",
"DCE IDL compiler version %1$s",
"Warning: Duplicate Protocol specification in endpoint list; \"%1$s\" ignored",
"Warning: Syntax error in endpoint specification \"%1$s\"",
"Warning: Extraneous punctuation character \"%1$s\" ignored ",
"Warning: The [handle] attribute of a parameter in a function pointer declaration is ignored",
"Warning: Identifier: %1$s too long; maximum is %2$lu chars",
"Warning: include filename must not contain a file extension",
"Warning: ACF include statement advised for definition of type %1$s",
"Warning: A size specifier is required; long assumed",
"Warning: The attributes [in_line] and [out_of_line] apply only to non-scalar types",
"Warning: Missing pointer class for %1$s; [ptr], [ref], or [unique] required",
"Warning: The attributes [max_is,length_is] or [size_is,last_is] used together",
"Warning: An attribute is defined multiple times",
"Warning: Generated name too long at line %1$lu.",
"Warning: At least one operation must have the [code] attribute",
"Warning: No endpoint can be found in the endpoint specification \"%1$s\"",
"Warning: Character constant cannot be portable across character sets",
"Warning: Semantic checking prevented by other reported errors",
"Warning: Old UUID format must be replaced with new format:",
"Warning: Object file for %1$s placed in current working directory",
"Warning: The attribute [%1$s] applied on type with [%2$s] set, [%3$s] assumed",
"Warning: The attribute [nocode] does not apply to server stub",
"Warning: File %1$s is a system-defined IDL filename",
"Pipes must be defined with a typedef",
"Declaration of %1$s cannot contain an anonymous type",
"An arm of a union cannot be or contain a [ref] pointer",
"Array elements cannot be conformant arrays or conformant structures",
"Array elements cannot be context handles",
"Array elements cannot be pipes",
"Array size information required for %1$s",
"Arrays can be conformant in the first dimension only",
"An array with a pointer attribute is valid only as a parameter",
"Use array syntax to declare multidimensional arrays",
"Arrays can be varying in the first dimension only",
"Arrays with [transmit_as] cannot be conformant or varying",
"The attribute is no longer allowed in this context; use translator",
"An attribute variable cannot be an indirect field reference",
"Invalid use of tag %1$s",
"The attribute [broadcast] is not valid on an operation with pipes",
"Case label type does not agree with discriminator type",
"Case label must be a constant from the enumeration of the discriminant",
"Structures containing conformant arrays must be passed by reference",
"The base type of a pipe cannot be a conformant type",
"A conformant field must be the last field in the structure",
"Conformant array or structure is invalid within a union",
"Interface attributes [auto_handle] and [implicit_handle] cannot occur together",
"The attributes [in_line] and [out_of_line] cannot occur together",
"The attributes [%1$s] and [%2$s] cannot occur together",
"The [represent_as] type %1$s conflicts with previously defined %2$s",
"Constant name: %1$s not found",
"Constant type does not agree with constant expression",
"A hyper constant type is not allowed",
"Missing \"}\" on interface declaration",
"Missing \"]\" on attribute list",
"Missing \"]\" on array bound",
"Missing result type on operation declaration",
"Missing type on parameter declaration",
"The base type of a pipe cannot be a [context_handle] type",
"Attribute [context_handle] only applies to void * types",
"Context handles are not valid as structure fields",
"Context handle is not valid as a member of a union",
"Definition of tag %1$s is not yet complete",
"Duplicate case label value",
"Unexpected end-of-file",
"Unexpected end-of-file near '%2$.*1$s'",
"Syntax error in attribute list",
"Data type %1$s must be defined in %2$s",
"File is not a directory: %1$s",
"File %1$s not found",
"The [first_is] parameter must have the [in] attribute",
"A [first_is] variable must be a small, short, or long integer",
"Floating point constants not supported",
"Function pointers are not valid as elements of conformant arrays",
"Function pointers are allowed only in local interfaces",
"Function pointer parameters cannot be of type handle_t",
"Function pointers in an operation must be [in] parameters",
"The base type of a pipe cannot be a function pointer",
"Function pointers are not valid as structure fields",
"Function pointers are not valid as members of unions",
"Function types are allowed only in local interfaces",
"Array elements cannot be of type handle_t",
"A [handle] binding parameter must be [in] or [in,out]",
"Pointers to type handle_t are valid only in parameter declarations",
"A handle_t as other than the first parameter requires a [transmit_as]",
"The base type of a pipe cannot be handle_t",
"A handle_t binding parameter must be an [in] parameter",
"Structure fields cannot be of type handle_t",
"Members of unions cannot be of type handle_t",
"A handle_t first parameter must not have [transmit_as] type",
"The attribute [idempotent] is not valid on an operation with pipes",
"The attribute [ignore] on array elements is not allowed",
"The attribute [ignore] is valid only for pointers",
"The attribute [%1$s] on a field is not allowed",
"The attribute [%1$s] on a parameter is not allowed",
"The attribute [%1$s] on a type is not allowed",
"The attribute [%1$s] on an operation is not allowed",
"The attribute [%1$s] on an interface is not allowed",
"The attribute [%1$s] on a union member is not allowed",
"An [implicit_handle] variable must either be of type handle_t or have the handle attribute",
"A nonlocal interface cannot import a local interface",
"V1 attributes are incompatible with this type",
"Interface attributes [code] and [nocode] cannot occur together",
"Integer division by zero",
"Interface attributes [in_line] and [out_of_line] cannot occur together",
"ACF interface name %1$s differs from IDL interface name %2$s",
"Integer value overflows %1$s",
"Integer constant %1$s is invalid",
"Interface UUID must be specified",
"Invalid array bound type",
"Invalid case label type",
"Invalid character literal",
"Invalid octal digit in %1$s",
"Could not invoke the C preprocessor",
"The attribute [out_of_line] is not allowed on parameters",
"Command option -%1$s %2$s is not valid",
"Invalid parameters on command line:",
"Pointers to context handles are valid only in parameter declarations",
"Pointers to pipes are valid only in parameter declarations",
"The [last_is] parameter must have the [in] attribute",
"The attributes [last_is] and [length_is] cannot occur together",
"A [last_is] variable must be a small, short, or long integer",
"The lower bound must not be greater than the upper bound",
"The [length_is] parameter must have the [in] attribute",
"A [length_is] variable must be a small, short, or long integer",
"The major version number is too large; the maximum is %1$lu",
"The attribute [max_is] cannot be applied to dimension %1$lu; upper bound is not dynamic",
"Maximum identifier length for interface name is %1$lu characters",
"Maximum identifier length for type with [transmit_as] is %1$lu characters",
"Maximum identifier length for [handle] type is %1$lu characters",
"Maximum identifier length for [context_handle] type is %1$lu characters",
"Maximum identifier length for pointed-to type is %1$lu characters",
"Maximum identifier length for pipe type is %1$lu characters",
"Maximum identifier length for [represent_as] type is %1$lu characters",
"Maximum identifier length for [out_of_line] type is %1$lu characters",
"A [max_is] parameter must have the [in] attribute",
"The attribute [max_is] or [size_is] is required",
"The attributes [max_is] and [size_is] cannot occur together",
"A [max_is] variable must be a small, short, or long integer",
"A [maybe] operation cannot have [out] parameters or a function result",
"The attribute [min_is] is required",
"The attribute [min_is] cannot be applied to dimension %1$lu; lower bound is not dynamic",
"A [min_is] parameter must have the [in] attribute",
"The minor version number is too large; the maximum is %1$lu",
"A [min_is] variable must be a small, short, or long integer",
"Name already declared: %1$s",
"Name is not a constant: %1$s",
"Name is not a field: %1$s",
"Name not found: %1$s",
"Name is not a parameter: %1$s",
"Name is not a type: %1$s",
"Name %1$s previously declared in file %2$s, line %3$lu",
"%1$sNLS message catalog version mismatch in \"%2$s\", Expected: \"%3$lu\", Actual: \"%4$s\"",
"%1$sError messages may be incorrect",
"Non-integer values are not allowed in expressions",
"The [align] attribute is not yet supported",
"The attribute [in(shape)] is not yet supported",
"Arrays with a nonzero lower bound are not yet supported",
"The attribute [out(shape)] is not yet supported",
"Attribute [unique] is not yet supported",
"Operation attributes [code] and [nocode] cannot occur together",
"Unable to open %1$s for read access",
"Unable to open %1$s for write access",
"Operation name %1$s referenced in ACF is not defined",
"An [out] conformant array must be a top-level parameter or under a non-[ref] pointer",
"Output parameters must be passed by reference",
"An [out,ptr] parameter is not valid",
"An [out] parameter or operation result cannot contain [unique] pointers",
"An operation result cannot be a pipe",
"Output parameters require an explicit top-level *",
"An [out,unique] parameter is not valid",
"The base type of a pipe cannot be a pipe type",
"Pipes are not valid as structure fields",
"Pipes are not valid as members of unions",
"A pipe cannot have a [transmit_as] type",
"A parameter with [%1$s] cannot be passed by value",
"A parameter must have either or both the [in] and [out] attributes",
"Parameter attributes [in_line] and [out_of_line] cannot occur together",
"Parameter name %1$s referenced in ACF operation %2$s is not defined",
"The attribute [ptr] is invalid on a binding handle parameter",
"The attribute [ptr] is valid only for pointer types or array parameter types",
"The base type of a pipe cannot be or contain a pointer",
"Incorrect syntax for pointer to conformant array",
"Full pointers to context handles are not allowed",
"The attribute [ptr] is not valid on pipe parameters",
"Pointers to [v1_enum] types are not allowed",
"Pointers to varying arrays are not allowed",
"void * must be used in conjunction with the [context_handle] attribute",
"The attribute [ref] is valid only for pointer types or array parameter types",
"A [ref] function result is not valid",
"Rename of %1$s to %2$s failed",
"Types with [represent_as] cannot be nested",
"Too many scoping levels",
"Size attributes can only be applied to array types",
"The attribute [size_is] cannot be applied to dimension %1$lu; upper bound is not dynamic",
"A [size_is] parameter must have the [in] attribute",
"The size attributes do not match the array dimension",
"The array size attribute variable %1$s cannot have the [ptr] or [unique] attributes",
"A [size_is] variable must be a small, short, or long integer",
"A size attribute variable must not have a represent_as type",
"A size attribute variable must not have a transmit_as type",
"The attribute [v1_array] must be in array, not pointer, syntax",
"A conformant [v1_array] must also be varying",
"The attribute [v1_array] is invalid for an array with more than 65535 elements",
"The attribute [v1_array] cannot occur with the [min_is] or [first_is] attributes",
"A [v1_array] can be conformant or varying in first dimension only",
"A [v1_array] cannot have a conformant lower bound",
"Arrays of strings are not allowed",
"The attribute [string] cannot be applied to a [v1_array]",
"The attribute [string] is valid only for one-dimensional array of valid base type",
"Structures with [transmit_as] or [represent_as] cannot be conformant",
"Unterminated string literal",
"The [v1_string] attribute can only be applied to a [v1_array]",
"A [v1_string] must be an array of char with fixed bounds",
"A [string] array cannot have varying array attributes",
"The attribute [%1$s] can occur at most once per operation",
"A parameter with [%1$s] must be an [out] parameter",
"An operation with [%1$s] must return a value of type error_status_t",
"A parameter with [%1$s] must be of type error_status_t",
"Syntax error",
"Syntax error near \"%2$.*1$s\"",
"Syntax error in UUID format",
"System error message: %1$s",
"Too many elements in %1$s",
"Too many endpoint specifications; Maximum is %1$lu",
"Type name: %1$s not found",
"Type attributes [in_line] and [out_of_line] cannot occur together",
"Type name %1$s referenced in ACF is not defined",
"Unbalanced parentheses",
"Unbalanced brackets",
"Unbalanced braces",
"A union discriminator type must be small, short, long, char, boolean, or enum",
"The attribute [unique] is invalid on a binding handle parameter",
"The attribute [unique] is valid only for pointer types or array parameter types",
"[unique] pointers to context handles are not allowed",
"A [unique] function result is not valid",
"Unknown attribute [%1$s]",
"Obsolete feature encountered; Use translator",
"The attribute [uuid] is invalid when the [local] attribute is specified",
"Variable declarations are not supported; declaration of %1$s ignored",
"void is valid only in an operation or a context handle pointer declaration",
"A type used in a [transmit_as] clause cannot have a [represent_as] type",
"A [transmit_as] or [represent_as] type cannot be a conformant array",
"The base type of a pipe cannot be a [transmit_as] type",
"A translated transmittable type cannot contain [%1$s] pointers",
"A type with [transmit_as] cannot have other type attributes",
"Command option -bug %1$lu conflicts with -no_bug %2$lu",
"Unterminated comment, end-of-file encountered",
"Compilation aborted",
"Internal IDL compiler error: Module %1$s, Line %2$lu",
"Command option -bug %1$lu is not known",
"Command option -no_bug %1$lu is not known",
"Reached maximum of %1$lu warnings; exiting",
"Command option %1$s does not take a value",
"Out of memory",
"Length of source filename and stub suffix exceed 8 chars",
"A source IDL filename is required",
"Unknown command line option: %1$s",
"Warning: Use of a nonencapsulated union requires %1$s",
"Warning: Use of [unique] pointers requires %1$s",
"An [in] or [in,out] union must have an [in] discriminator",
"An [in,out] or [out] union must have an [out] discriminator",
"A [switch_is] variable must not have a [represent_as] type",
"A [switch_is] variable must not have a [transmit_as] type",
"An encapsulated union member cannot have the [%1$s] attribute",
"Arrays of nonencapsulated unions are not allowed",
"A [represent_as] type cannot be a nonencapsulated union",
"A nonencapsulated union cannot have a [represent_as] type",
"A nonencapsulated union declaration must have a [switch_is] attribute",
"The union switch variable %1$s cannot be a [ptr] or [unique] pointer",
"A nonencapsulated union type must have a [switch_type] attribute",
"A [transmit_as] type cannot be a nonencapsulated union",
"A nonencapsulated union cannot have a [transmit_as] type",
"Cannot have more than one level of indirection to a nonencapsulated union",
"A [switch_is] attribute is only valid on a nonencapsulated union",
"Data type of [switch_is] variable %1$s does not agree with [switch_type] %2$s",
"A [switch_type] attribute is only valid on a nonencapsulated union type",
"Data type of %1$s must be a named TPS_STDL_ type",
"A structure field cannot be of a presented type for which the transmitted type is conformant",
"A type with the [represent_as] attribute cannot be conformant",
"An arm of a union cannot be or contain a [unique] pointer",
"Warning: FORTRAN INTEGER*%1$lu used for IDL pointer type",
"Warning: FORTRAN INTEGER*4 used for IDL unsigned long",
"Warning: Conformant structures not supported in target language",
"Warning: Conformant strings not supported in target language",
"Warning: Character doesn't map to target language",
"Warning: Pipes not supported for target language",
"Warning: Non-scalar function result converted to trailing [out] parameter",
"Target language supports maximum of %1$lu array dimensions",
"Warning: Name %1$s differs from a previous name only in case",
"Warning: Attribute [%1$s] not supported for target language",
"Array function results are not allowed",
"Attribute [%1$s] cannot be applied to a void * type",
"The [handle] attribute is valid only on transmittable types",
"Warning: Forward tag reference %1$s in this declaration is not ANSI C compliant",
"Attribute cannot be used more than once",
"Type with [%1$s] cannot be used in definition of type with [%2$s]",
"Warning: Use of nonzero array lower bound requires %1$s",
"Creating template file %1$s",
"Warning: Use of conformant minor array dimension requires %1$s",
"Warning: Use of varying minor array dimension requires %1$s",
"Translation routines for [represent_as] type %1$s",
"Translation routines for [transmit_as] type %1$s",
"Customized binding routines for [handle] type %1$s",
"Rundown routine for [context_handle] type %1$s",
"Support routines for interface %1$s",
"Support routines and Remote Procedure Implementations for interface %1$s",
"Implementation of Remote Procedures for %1$s",
"Operation with [encode] must have at least one [in] or [in,out] parameter",
"Operation with [decode] must have at least one [out] or [in,out] parameter",
"Warning: Operation with [reflect_deletions] has no [in] or [in,out] full pointers",
"Warning: Operation with [encode] has [out]-only parameter %1$s",
"Warning: Operation with [decode] has [in]-only parameter %1$s",
"Operation with [encode,decode] must have all [in,out] parameters",
"Operation with [encode] or [decode] may not contain pipe parameters",
"Operation with [encode] or [decode] must use explicit binding",
"Exception name %1$s referenced in ACF is not defined",
"Invalid file specification: %1$s",
"File specification required for %1$s",
"Warning: Operation with [cs_tag_rtn] contains no codeset tag parameters",
"Types with the [%1$s] attribute cannot be nested",
"The [%1$s] attribute cannot be duplicated in the same parameter list",
"Operation with [in] [cs_char] data requires [cs_stag] parameter",
"Operation with [out] [cs_char] data requires [cs_rtag] parameter",
"Array attribute variable cannot be used for both [cs_char] and non-[cs_char] arrays",
"An [in,size_is] parameter for an [out,cs_char] array cannot be used for other array attributes",
"A [size_is] or [max_is] attribute cannot be applied to a pointer to a [cs_char] type",
"An array with [%1$s] base type cannot have the [ptr] or [unique] attributes",
"A [transmit_as] transmitted type cannot contain a [%1$s] type",
"A [cs_stag] parameter must precede any [in] [cs_char] data in a parameter list",
"A [cs_rtag] parameter must precede any [out] [cs_char] data in a parameter list",
"A [handle] binding parameter cannot contain a [%1$s] type",
"The base type of a pipe cannot be or contain a [%1$s] type",
"Arrays of [%1$s] type cannot be multidimensional",
"Arrays of [%1$s] type can only use the [size_is] and [length_is] array attributes",
"Type with [%1$s] cannot be or contain type with [%2$s]",
"Type with [%1$s] must resolve to byte or structure containing only byte fields",
"Tag parameters must have type unsigned long int passed by value or reference",
"Maximum identifier length for [%1$s] type is %2$lu characters",
"Warning: Use of user-defined exceptions requires %1$s",
"Warning: Use of [%1$s] attribute requires %2$s",
"A [%1$s] parameter must have the [%2$s] attribute",
"Warning: Use of C preprocessor directive requires %1$s",
"Warning: Use of anonymous %1$s may not be portable across C compilers",
"Warning: A [fault_status] parameter has no utility in this operation",
"Only objects can inherit interfaces",
"Interface ref not allowed",
"Warning: Pointer attributes are ignored for interface references",
"Inherited interface '%1$s' not defined/imported",
"Expression must be constant",
"exp is null??",
"Only simple expressions allowed for now",
"The upper bound of a [range] attribute must be greater than the lower bound",
"A [range] attribute is only valid on integral types other than hyper, a type identifier to an integral type, an enumerated type, or a pipe type name",
"A constant [size_is] or [length_is] requires a constant [min_is] or [first_is]",
"Correlation checking will not be performed for attributes that occur after the field or parameter they modify",
