/*
 * lwerror-table-krb5.h is generated from krb5error-table.h
 * using lwkrb5str.  Do not modify lwerror-table-krb5.h
 * directly.  Modify krb5error-table.h, then run lwkrb5str.
 */

S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_BAD_TIMEFORMAT, -1, "ASN.1 failed call to system time library" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_MISSING_FIELD, -1, "ASN.1 structure is missing a required field" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_MISPLACED_FIELD, -1, "ASN.1 unexpected field number" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_TYPE_MISMATCH, -1, "ASN.1 type numbers are inconsistent" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_OVERFLOW, -1, "ASN.1 value too large" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_OVERRUN, -1, "ASN.1 encoding ended unexpectedly" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_BAD_ID, -1, "ASN.1 identifier doesn't match expected value" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_BAD_LENGTH, -1, "ASN.1 length doesn't match expected value" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_BAD_FORMAT, -1, "ASN.1 badly-formatted encoding" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_PARSE_ERROR, -1, "ASN.1 parse error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_BAD_GMTIME, -1, "ASN.1 bad return from gmtime" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_MISMATCH_INDEF, -1, "ASN.1 non-constructed indefinite encoding" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ASN1_MISSING_EOC, -1, "ASN.1 missing expected EOC" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB524_KRB4_DISABLED, -1, "Kerberos version 4 support is disabled" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_NONE, -1, "No error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_NAME_EXP, -1, "Client's entry in database has expired" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SERVICE_EXP, -1, "Server's entry in database has expired" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_BAD_PVNO, -1, "Requested protocol version not supported" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_C_OLD_MAST_KVNO, -1, "Client's key is encrypted in an old master key" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_S_OLD_MAST_KVNO, -1, "Server's key is encrypted in an old master key" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN, -1, "Client not found in Kerberos database" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN, -1, "Server not found in Kerberos database" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_PRINCIPAL_NOT_UNIQUE, -1, "Principal has multiple entries in Kerberos database" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_NULL_KEY, -1, "Client or server has a null key" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CANNOT_POSTDATE, -1, "Ticket is ineligible for postdating" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_POLICY, -1, "KDC policy rejects request" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_BADOPTION, -1, "KDC can't fulfill requested option" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_ETYPE_NOSUPP, -1, "KDC has no support for encryption type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SUMTYPE_NOSUPP, -1, "KDC has no support for checksum type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_PADATA_TYPE_NOSUPP, -1, "KDC has no support for padata type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_TRTYPE_NOSUPP, -1, "KDC has no support for transited type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SERVICE_REVOKED, -1, "Credentials for server have been revoked" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_TGT_REVOKED, -1, "TGT has been revoked" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CLIENT_NOTYET, -1, "Client not yet valid - try again later" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SERVICE_NOTYET, -1, "Server not yet valid - try again later" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_PREAUTH_REQUIRED, -1, "Additional pre-authentication required" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SERVER_NOMATCH, -1, "Requested server and ticket don't match" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_SVC_UNAVAILABLE, -1, "A service is not available that is required to process the request" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_TKT_EXPIRED, -1, "Ticket expired" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_TKT_NYV, -1, "Ticket not yet valid" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_REPEAT, -1, "Request is a replay" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_NOT_US, -1, "The ticket isn't for us" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADMATCH, -1, "Ticket/authenticator don't match" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADADDR, -1, "Incorrect net address" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADVERSION, -1, "Protocol version mismatch" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_MSG_TYPE, -1, "Invalid message type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_MODIFIED, -1, "Message stream modified" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADORDER, -1, "Message out of order" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_ILL_CR_TKT, -1, "Illegal cross-realm ticket" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADKEYVER, -1, "Key version is not available" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_NOKEY, -1, "Service key not available" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_MUT_FAIL, -1, "Mutual authentication failed" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADDIRECTION, -1, "Incorrect message direction" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_METHOD, -1, "Alternative authentication method required" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_BADSEQ, -1, "Incorrect sequence number in message" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_INAPP_CKSUM, -1, "Inappropriate type of checksum in message" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_PATH_NOT_ACCEPTED, -1, "Policy rejects transited path" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_ERR_RESPONSE_TOO_BIG, -1, "Response too big for UDP, retry with TCP" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_ERR_GENERIC, -1, "Generic error (see e-text)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_ERR_FIELD_TOOLONG, -1, "Field is too long for this implementation" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CLIENT_NOT_TRUSTED, -1, "Client not trusted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_KDC_NOT_TRUSTED, -1, "KDC not trusted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_INVALID_SIG, -1, "Invalid signature" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_DH_KEY_PARAMETERS_NOT_ACCEPTED, -1, "Key parameters not accepted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CERTIFICATE_MISMATCH, -1, "Certificate mismatch" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CANT_VERIFY_CERTIFICATE, -1, "Can't verify certificate" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_INVALID_CERTIFICATE, -1, "Invalid certificate" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_REVOKED_CERTIFICATE, -1, "Revoked certificate" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_REVOCATION_STATUS_UNKNOWN, -1, "Revocation status unknown" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_REVOCATION_STATUS_UNAVAILABLE, -1, "Revocation status unavailable" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_CLIENT_NAME_MISMATCH, -1, "Client name mismatch" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_KDC_NAME_MISMATCH, -1, "KDC name mismatch" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_INCONSISTENT_KEY_PURPOSE, -1, "Inconsistent key purpose" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_DIGEST_IN_CERT_NOT_ACCEPTED, -1, "Digest in certificate not accepted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_PA_CHECKSUM_MUST_BE_INCLUDED, -1, "Checksum must be included" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_DIGEST_IN_SIGNED_DATA_NOT_ACCEPTED, -1, "Digest in signed-data not accepted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KDC_ERR_PUBLIC_KEY_ENCRYPTION_NOT_SUPPORTED, -1, "Public key encryption not supported" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_RCSID, -1, "$Id: krb5_err.et 22254 2009-04-15 20:07:45Z tlyu $" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LIBOS_BADLOCKFLAG, -1, "Invalid flag for file lock mode" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LIBOS_CANTREADPWD, -1, "Cannot read password" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LIBOS_PWDINTR, -1, "Password read interrupted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PARSE_ILLCHAR, -1, "Illegal character in component name" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PARSE_MALFORMED, -1, "Malformed representation of principal" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CONFIG_CANTOPEN, -1, "Can't open/find Kerberos configuration file" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CONFIG_BADFORMAT, -1, "Improper format of Kerberos configuration file" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CONFIG_NOTENUFSPACE, -1, "Insufficient space to return complete information" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_BADMSGTYPE, -1, "Invalid message type specified for encoding" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_BADNAME, -1, "Credential cache name malformed" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_UNKNOWN_TYPE, -1, "Unknown credential cache type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_NOTFOUND, -1, "Matching credential not found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_END, -1, "End of credential cache reached" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NO_TKT_SUPPLIED, -1, "Request did not supply a ticket" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_WRONG_PRINC, -1, "Wrong principal in request" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_TKT_INVALID, -1, "Ticket has invalid flag set" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PRINC_NOMATCH, -1, "Requested principal and ticket don't match" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KDCREP_MODIFIED, -1, "KDC reply did not match expectations" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KDCREP_SKEW, -1, "Clock skew too great in KDC reply" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_IN_TKT_REALM_MISMATCH, -1, "Client/server realm mismatch in initial ticket request" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROG_ETYPE_NOSUPP, -1, "Program lacks support for encryption type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROG_KEYTYPE_NOSUPP, -1, "Program lacks support for key type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_WRONG_ETYPE, -1, "Requested encryption type not used in message" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROG_SUMTYPE_NOSUPP, -1, "Program lacks support for checksum type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_REALM_UNKNOWN, -1, "Cannot find KDC for requested realm" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SERVICE_UNKNOWN, -1, "Kerberos service unknown" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NO_LOCALNAME, -1, "No local name found for principal name" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_MUTUAL_FAILED, -1, "Mutual authentication failed" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_TYPE_EXISTS, -1, "Replay cache type is already registered" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_MALLOC, -1, "No more memory to allocate (in replay cache code)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_TYPE_NOTFOUND, -1, "Replay cache type is unknown" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_UNKNOWN, -1, "Generic unknown RC error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_REPLAY, -1, "Message is a replay" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO, -1, "Replay I/O operation failed XXX" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_NOIO, -1, "Replay cache type does not support non-volatile storage" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_PARSE, -1, "Replay cache name parse/format error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_EOF, -1, "End-of-file on replay cache I/O" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_MALLOC, -1, "No more memory to allocate (in replay cache I/O code)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_PERM, -1, "Permission denied in replay cache code" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_IO, -1, "I/O error in replay cache i/o code" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_UNKNOWN, -1, "Generic unknown RC/IO error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_IO_SPACE, -1, "Insufficient system space to store replay information" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_TRANS_CANTOPEN, -1, "Can't open/find realm translation file" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_TRANS_BADFORMAT, -1, "Improper format of realm translation file" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LNAME_CANTOPEN, -1, "Can't open/find lname translation database" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LNAME_NOTRANS, -1, "No translation available for requested principal" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LNAME_BADFORMAT, -1, "Improper format of translation database entry" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CRYPTO_INTERNAL, -1, "Cryptosystem internal error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_BADNAME, -1, "Key table name malformed" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_UNKNOWN_TYPE, -1, "Unknown Key table type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_NOTFOUND, -1, "Key table entry not found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_END, -1, "End of key table reached" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_NOWRITE, -1, "Cannot write to specified key table" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_IOERR, -1, "Error writing to key table" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NO_TKT_IN_RLM, -1, "Cannot find ticket for requested realm" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5DES_BAD_KEYPAR, -1, "DES key has bad parity" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5DES_WEAK_KEY, -1, "DES key is a weak key" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_BAD_ENCTYPE, -1, "Bad encryption type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_BAD_KEYSIZE, -1, "Key size is incompatible with encryption type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_BAD_MSIZE, -1, "Message size is incompatible with encryption type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_TYPE_EXISTS, -1, "Credentials cache type is already registered." )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_TYPE_EXISTS, -1, "Key table type is already registered." )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_IO, -1, "Credentials cache I/O operation failed XXX" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_FCC_PERM, -1, "Credentials cache permissions incorrect" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_FCC_NOFILE, -1, "No credentials cache found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_FCC_INTERNAL, -1, "Internal credentials cache error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_WRITE, -1, "Error writing to credentials cache" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_NOMEM, -1, "No more memory to allocate (in credentials cache code)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_FORMAT, -1, "Bad format in credentials cache" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_NOT_KTYPE, -1, "No credentials found with supported encryption types" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_INVALID_FLAGS, -1, "Invalid KDC option combination (library internal error)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NO_2ND_TKT, -1, "Request missing second ticket" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NOCREDS_SUPPLIED, -1, "No credentials supplied to library routine" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SENDAUTH_BADAUTHVERS, -1, "Bad sendauth version was sent" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SENDAUTH_BADAPPLVERS, -1, "Bad application version was sent (via sendauth)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SENDAUTH_BADRESPONSE, -1, "Bad response (during sendauth exchange)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SENDAUTH_REJECTED, -1, "Server rejected authentication (during sendauth exchange)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PREAUTH_BAD_TYPE, -1, "Unsupported preauthentication type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PREAUTH_NO_KEY, -1, "Required preauthentication key not supplied" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PREAUTH_FAILED, -1, "Generic preauthentication failure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RCACHE_BADVNO, -1, "Unsupported replay cache format version number" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CCACHE_BADVNO, -1, "Unsupported credentials cache format version number" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KEYTAB_BADVNO, -1, "Unsupported key table format version number" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROG_ATYPE_NOSUPP, -1, "Program lacks support for address type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_RC_REQUIRED, -1, "Message replay detection requires rcache parameter" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_BAD_HOSTNAME, -1, "Hostname cannot be canonicalized" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_HOST_REALM_UNKNOWN, -1, "Cannot determine realm for host" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SNAME_UNSUPP_NAMETYPE, -1, "Conversion to service principal undefined for name type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5KRB_AP_ERR_V4_REPLY, -1, "Initial Ticket response appears to be Version 4 error" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_REALM_CANT_RESOLVE, -1, "Cannot resolve network address for KDC in requested realm" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_TKT_NOT_FORWARDABLE, -1, "Requesting ticket can't get forwardable tickets" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_FWD_BAD_PRINCIPAL, -1, "Bad principal name while trying to forward credentials" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_GET_IN_TKT_LOOP, -1, "Looping detected inside krb5_get_in_tkt" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CONFIG_NODEFREALM, -1, "Configuration file does not specify default realm" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SAM_UNSUPPORTED, -1, "Bad SAM flags in obtain_sam_padata" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SAM_INVALID_ETYPE, -1, "Invalid encryption type in SAM challenge" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SAM_NO_CHECKSUM, -1, "Missing checksum in SAM challenge" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_SAM_BAD_CHECKSUM, -1, "Bad checksum in SAM challenge" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_NAME_TOOLONG, -1, "Keytab name too long" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_KVNONOTFOUND, -1, "Key version number for principal in key table is incorrect" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_APPL_EXPIRED, -1, "This application has expired" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_LIB_EXPIRED, -1, "This Krb5 library has expired" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CHPW_PWDNULL, -1, "New password cannot be zero length" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CHPW_FAIL, -1, "Password change failed" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KT_FORMAT, -1, "Bad format in keytab" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_NOPERM_ETYPE, -1, "Encryption type not permitted" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CONFIG_ETYPE_NOSUPP, -1, "No supported encryption types (config file error?)" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_OBSOLETE_FN, -1, "Program called an obsolete, deleted function" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_EAI_FAIL, -1, "unknown getaddrinfo failure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_EAI_NODATA, -1, "no data available for host/domain name" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_EAI_NONAME, -1, "host/domain name not found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_EAI_SERVICE, -1, "service name unknown" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_NUMERIC_REALM, -1, "Cannot determine realm for numeric host address" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_BAD_S2K_PARAMS, -1, "Invalid key generation parameters from KDC" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_ERR_NO_SERVICE, -1, "service not available" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_READONLY, -1, "Ccache function not supported: read-only ccache type" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_CC_NOSUPP, -1, "Ccache function not supported: not implemented" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_DELTAT_BADFORMAT, -1, "Invalid format of Kerberos lifetime or clock skew string" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PLUGIN_NO_HANDLE, -1, "Supplied data not handled by this plugin" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PLUGIN_OP_NOTSUPP, -1, "Plugin does not support the operaton" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_NONE, -1, "Kerberos V5 magic number table" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PRINCIPAL, -1, "Bad magic number for krb5_principal structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_DATA, -1, "Bad magic number for krb5_data structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_KEYBLOCK, -1, "Bad magic number for krb5_keyblock structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CHECKSUM, -1, "Bad magic number for krb5_checksum structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENCRYPT_BLOCK, -1, "Bad magic number for krb5_encrypt_block structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENC_DATA, -1, "Bad magic number for krb5_enc_data structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CRYPTOSYSTEM_ENTRY, -1, "Bad magic number for krb5_cryptosystem_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CS_TABLE_ENTRY, -1, "Bad magic number for krb5_cs_table_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CHECKSUM_ENTRY, -1, "Bad magic number for krb5_checksum_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AUTHDATA, -1, "Bad magic number for krb5_authdata structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_TRANSITED, -1, "Bad magic number for krb5_transited structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENC_TKT_PART, -1, "Bad magic number for krb5_enc_tkt_part structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_TICKET, -1, "Bad magic number for krb5_ticket structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AUTHENTICATOR, -1, "Bad magic number for krb5_authenticator structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_TKT_AUTHENT, -1, "Bad magic number for krb5_tkt_authent structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CREDS, -1, "Bad magic number for krb5_creds structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_LAST_REQ_ENTRY, -1, "Bad magic number for krb5_last_req_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PA_DATA, -1, "Bad magic number for krb5_pa_data structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_KDC_REQ, -1, "Bad magic number for krb5_kdc_req structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENC_KDC_REP_PART, -1, "Bad magic number for krb5_enc_kdc_rep_part structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_KDC_REP, -1, "Bad magic number for krb5_kdc_rep structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ERROR, -1, "Bad magic number for krb5_error structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AP_REQ, -1, "Bad magic number for krb5_ap_req structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AP_REP, -1, "Bad magic number for krb5_ap_rep structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AP_REP_ENC_PART, -1, "Bad magic number for krb5_ap_rep_enc_part structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_RESPONSE, -1, "Bad magic number for krb5_response structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAFE, -1, "Bad magic number for krb5_safe structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PRIV, -1, "Bad magic number for krb5_priv structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PRIV_ENC_PART, -1, "Bad magic number for krb5_priv_enc_part structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CRED, -1, "Bad magic number for krb5_cred structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CRED_INFO, -1, "Bad magic number for krb5_cred_info structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CRED_ENC_PART, -1, "Bad magic number for krb5_cred_enc_part structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PWD_DATA, -1, "Bad magic number for krb5_pwd_data structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ADDRESS, -1, "Bad magic number for krb5_address structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_KEYTAB_ENTRY, -1, "Bad magic number for krb5_keytab_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CONTEXT, -1, "Bad magic number for krb5_context structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_OS_CONTEXT, -1, "Bad magic number for krb5_os_context structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ALT_METHOD, -1, "Bad magic number for krb5_alt_method structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ETYPE_INFO_ENTRY, -1, "Bad magic number for krb5_etype_info_entry structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_DB_CONTEXT, -1, "Bad magic number for krb5_db_context structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_AUTH_CONTEXT, -1, "Bad magic number for krb5_auth_context structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_KEYTAB, -1, "Bad magic number for krb5_keytab structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_RCACHE, -1, "Bad magic number for krb5_rcache structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_CCACHE, -1, "Bad magic number for krb5_ccache structure" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PREAUTH_OPS, -1, "Bad magic number for krb5_preauth_ops" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAM_CHALLENGE, -1, "Bad magic number for krb5_sam_challenge" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAM_CHALLENGE_2, -1, "Bad magic number for krb5_sam_challenge_2" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAM_KEY, -1, "Bad magic number for krb5_sam_key" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENC_SAM_RESPONSE_ENC, -1, "Bad magic number for krb5_enc_sam_response_enc" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_ENC_SAM_RESPONSE_ENC_2, -1, "Bad magic number for krb5_enc_sam_response_enc" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAM_RESPONSE, -1, "Bad magic number for krb5_sam_response" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_SAM_RESPONSE_2, -1, "Bad magic number for krb5_sam_response 2" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PREDICTED_SAM_RESPONSE, -1, "Bad magic number for krb5_predicted_sam_response" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_PASSWD_PHRASE_ELEMENT, -1, "Bad magic number for passwd_phrase_element" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_GSS_OID, -1, "Bad magic number for GSSAPI OID" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_KV5M_GSS_QUEUE, -1, "Bad magic number for GSSAPI QUEUE" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_VERSION, -1, "Profile version 0.0" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_NODE, -1, "Bad magic value in profile_node" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_NO_SECTION, -1, "Profile section not found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_NO_RELATION, -1, "Profile relation not found" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_ADD_NOT_SECTION, -1, "Attempt to add a relation to node which is not a section" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_SECTION_WITH_VALUE, -1, "A profile section header has a non-zero value" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_LINK_LIST, -1, "Bad linked list in profile structures" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_GROUP_LVL, -1, "Bad group level in profile strctures" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_PARENT_PTR, -1, "Bad parent pointer in profile strctures" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_ITERATOR, -1, "Bad magic value in profile iterator" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_SET_SECTION_VALUE, -1, "Can't set value on section node" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_EINVAL, -1, "Invalid argument passed to profile library" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_READ_ONLY, -1, "Attempt to modify read-only profile" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_SECTION_NOTOP, -1, "Profile section header not at top level" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_SECTION_SYNTAX, -1, "Syntax error in profile section header" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_RELATION_SYNTAX, -1, "Syntax error in profile relation" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_EXTRA_CBRACE, -1, "Extra closing brace in profile" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MISSING_OBRACE, -1, "Missing open brace in profile" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_PROFILE, -1, "Bad magic value in profile_t" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_SECTION, -1, "Bad magic value in profile_section_t" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_TOPSECTION_ITER_NOSUPP, -1, "Iteration through all top level section not supported" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_INVALID_SECTION, -1, "Invalid profile_section object" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_END_OF_SECTIONS, -1, "No more sections" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_NAMESET, -1, "Bad nameset passed to query routine" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_NO_PROFILE, -1, "No profile file open" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_FILE, -1, "Bad magic value in profile_file_t" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_FAIL_OPEN, -1, "Couldn't open profile file" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_EXISTS, -1, "Section already exists" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_BOOLEAN, -1, "Invalid boolean value" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_BAD_INTEGER, -1, "Invalid integer value" )
S ( LW_STATUS_MESSAGE_NOT_FOUND, LW_ERROR_KRB5_PROF_MAGIC_FILE_DATA, -1, "Bad magic value in profile_file_data_t" )
