.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PBIS" "7" "August 2018" "" ""
.
.SH "NAME"
\fBpbis\fR \- A suite of tools and services for joining Linux, Unix, and OS X clients to Active Directory domains
.
.SH "DESCRIPTION"
PowerBroker Identity Services Open (PBIS) is a set of tools and services to enable joining hosts to an Active Directory (AD) domain in a single step\. The software performs all the necessary system management configuration to enable PAM aware host services to authenticate AD domain users and honour the user\'s existing set of domain group memberships\.
.
.SH "SUPPORT"
PBIS is available in Open and Enterprise editions\.
.
.P
Information about PBIS Open can be found at PBIS Open \fIhttps://github\.com/BeyondTrust/pbis\-open\fR\. Information on PBIS Enterprise can be found at PBIS Enterprise \fIhttps://www\.beyondtrust\.com/products/powerbroker\-identity\-services\-ad\-bridge/\fR
.
.SH "SEE ALSO"
domainjoin\-cli(8)
